### ISSUE TITLE
git diff plugin

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1062]
Git allows plugging custom diff comparators. We can use refmt to output AST-aware diffs.

**Comment by tekknolagi** [comment]
@chenglou What do you mean exactly? So you could diff between OCaml and Reason?

**Comment by chenglou** [comment]
git allows pluggable diffing algorithm: `git difftool --extcmd myDiffTool ...`. We can try writing our own (low pri) that takes in the two files, parse into ast, do the ast diffing, then output the pretty-printed diff. This might allow a more accurate diff.

**Comment by tekknolagi** [comment]
Is there an AST diff algorithm?

**Comment by sgrove** [comment]
https://github.com/GumTreeDiff/gumtree is a good example of this, worth playing with their examples to see what diffs could be like.

**Comment by anmonteiro** [comment]
Very easy to do this today with dune
