### ISSUE TITLE
Accept any past version of the syntax

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1082]
We should truly attempt this at one point and deliver on the original idea.

A reason file would be:

```reason
//@@ reason v.1.9.3-or-hash

let a = 1;
```

(that first line's just a special syntax, that can desugar to e.g. a ppx or whatever)

And our refmt, even if it's at version 3.0.0, would recognize this syntax and convert it over.

Reup kinda does this but has been neglected; also, this concept does it dynamically.

**Comment by tekknolagi** [comment]
How would this work? Keep the git repo in the install? Or just all past versions?

**Comment by jaredly** [comment]
One way to do this would be to have a global cache of past refmt versions, and download on demand.
