### ISSUE TITLE
Atom compile errors aren't as helpful as Terminal output

### ISSUE THREAD

**Issue by ccorcos** [reasonml/reason#1124]
I was investigating a syntax error:

![ejwfwvsohcamamc7cadkq4r6g4iejuojrdmpzd59z77qnbfa1ceyeapyty40d81cm7eqg1g7ax4n60ipzjfcjqd2yxa-wesd3ozg1-rcbjds9itlibhnnn6v8par06fr0zv6_qej4yl0](https://cloud.githubusercontent.com/assets/1794527/23670900/26bfedae-031e-11e7-861f-9d3e52409742.png)

but I couldnt find any useful messages in here:

![ejwfwveogyamanc7caaqdejxngqjmikltgyfy-6-977mmzfzzke6zapytyk8dyvkm7dqg3o7ah6n2mi3znvcjrt2ffayxeplqhecw8mhcj4o4gudx1yijegonv7u_ol29gz-fwjlius](https://cloud.githubusercontent.com/assets/1794527/23670914/304585c8-031e-11e7-861e-5f5ab5fec6e5.png)

but when I look at the compiler output in my Terminal, the error is a lot more useful:

```
File "/Users/chet/Code/Reason/cube/src/tutorial.re", line 106, characters 11-15:
Error: 19: <UNKNOWN SYNTAX ERROR>
```

its complaining that `type` is a reserved word... it would be great to see these errors in the editor.

**Comment by tekknolagi** [comment]
I wonder if it's possible to let `type` be used in JSX as you did. @jordwalke ?
