### ISSUE TITLE
[Bikeshed] Make Immutable.re's Vector type the default list type in Reason

### ISSUE THREAD

**Issue by bordoley** [reasonml/reason#1195]
Food for thought here. There was discussion on discord about the OCaml list not actually being a fundamental data structure, and in many ways a suboptimal choice for the default list type. 

List has the following benefits:
* O(1) prepends to the head of the list
* O(1) access to the head of the list
* Simple recursive traversal

List however is significantly limited in support for other operations:
* O(N) indexed lookups
* Concantenation of two list is O(N) and typically not tail recursive
* Take operations require O(N) copies

Ideally the default Reason List/Array structure would provide an efficient API that is mostly compatible with the existing array semantics in Javascript but is also efficiently immutable. Immutable.re includes such a data-structure. Vector is implemented as an [RRB tree](https://infoscience.epfl.ch/record/169879/files/RMTrees.pdf) with some added tail and head optimizations. It supports efficient appends, prepends, indexing, updates, and can be improved to support arbitrary efficient insert, removeAt and concatenation, effectively implementing the full range of array spread operations, but far more efficiently than the standard javascript equivalents. 

Consider the following hypothetical operations:
```
let x = really big array (say n = 1000)
let y = [| 1, ...x, ...x, 2, 3, 4, ...x |];
```
In javascript, such syntax would result in copying x at least 3 times along with all the resulting appending operations. It obviously can be optimized in this simple case, but over time use of such array spreads continues resulting in O(N) copying. By contrast if implemented as an RRB tree (vector), This operation becomes efficient, with at most 7 copies of n=32 arrays (for vectors with 2 billion items) per concatenation.

Another significant benefit of such an immutable array syntax is that it can be used to pass var arg like arguments to functions without the necessity for defensive copying. Providing the syntactic benefits of list with the performance benefits for arrays.

Also this is not a completely hypothetical solution, the elm programming language utilized RRB trees as its default data-structure for arrays: http://elm-lang.org/blog/announce/0.12.1
 
Related issues: 
* https://github.com/facebook/reason/issues/971
* https://github.com/facebook/reason/issues/873

**Comment by yunxing** [comment]
Still reading the RRB paper. This is doable, preferably we can integrate that into js_ppx transformation and then with bsb.

**Comment by bordoley** [comment]
@yunxing: It would require me completing support for concat, insert and removeAt, but there are existing implementations that I can reference that will help. Another option is to pull the core code for vector out of Immutable.re and provide it as part of a minimal base lib, which Imm.re can add sugar on top of in terms of nice APIs.
