### ISSUE TITLE
Auto-break records with two or more fields

### ISSUE THREAD

**Issue by IwanKaramazow** [reasonml/reason#1207]
Refmt gave me the following:
```reason
type t 'a = {size: int, buffer: array 'a, pre: int, post: int};
```
This doesn't linebreak because the line-length isn't exceeded.
For readability purposes, shouldn't this break over multiple lines?
```reason
type t 'a = {
  size: int,
  buffer: array 'a,
  pre: int,
  post: int
};
```
I would propose that all records with two or more fields break over multiple lines for readability & ease of extension. Any opinions on this one?

**Comment by yunxing** [comment]
To me it looks better than putting them into one line.

Since we don't see many single field records, maybe we can always break.

**Comment by andreypopp** [comment]
I propose breaking record into multiple lines if in input there was a break somewhere before the closing `}`. The idea is that a line break in input should signify an intent to format a record with line breaks.

#### Should break
```
type t = {
  a: int, b: int};
```
```
type t = {a: int,
  b: int};
```
---
```
type t = {
  a: int,
  b: int
};
```
#### Should NOT break
```
type t = {a: int, b: int};
```
```
type t = {a: int, b: int
};
```
---
```
type t = {a: int, b: int};
```

**Comment by andreypopp** [comment]
Btw with the current syntax #1216 was invalidated and `refmt` doesn't break records with two or more fields in it.

Also the thing I proposed mimics `prettier` behaviour which I'm personally enjoying.

**Comment by IwanKaramazow** [comment]
Shouldn't be too hard, I'll see what I can do

**Comment by anmonteiro** [comment]
works in the latest reason
