### ISSUE TITLE
Change `foo . foo` to `forall foo . foo`

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1245]

**Comment by bobzhang** [comment]
can we find a way to avoid introducing a new keyword

**Comment by chenglou** [comment]
Avoiding new keywords would be nice. No idea how in this situation though

**Comment by OvermindDL1** [comment]
Isn't the dot `.` in this case already stating that to the left are the generic type names anyway?  What is the point in adding `forall` too?

**Comment by jordwalke** [comment]
@OvermindDL1  : The purpose was merely to improve readability. Most people new to Reason/OCaml have no idea what the `.` means.

**Comment by hcarty** [comment]
@jordwalke Isn't the same true for `forall`? In either case it's more likely than not a new concept.

**Comment by bsansouci** [comment]
I'd be in favor of this. I think the dot isn't clear at all, even having used this feature. Adding a "forall" helps me remember what the heck this language feature is.

**Comment by bobzhang** [comment]
how about just using `for`, or `for .. in`
```
for 'a in 'a -> 'a 
```

**Comment by bsansouci** [comment]
@bobzhang I like the idea of replacing `.` with `in`. But `'a -> 'a` already means `for a single 'a`, so I still prefer having `forall a in a -> a`. Though it is a poweruser feature to have (forall types vs for a single type).

**Comment by bobzhang** [comment]
let a in a -> a ? The cost of introducing  a keyword is quite high, think about List.forall
