### ISSUE TITLE
Better Error suggestion: Why does the compiler think token should be type X instead of type Y?

### ISSUE THREAD

**Issue by sgrove** [reasonml/reason#1262]
Right now I might have some code like:

```rust
ytLocalization: Lazy.t (Graphql_lwt.Schema.typ unit (option YTD.localization)) =
makeField "title" (
                fun (ctx: Common.schemaContext) (ytLocalization: YTD.localization) =>
                  YTD.(ytLocalization.title) /* [1] /*
              )
```

And get an error at [1]: `Error: This pattern matches values of type Common.schemaContext but a pattern was expected which matches values of type unit`

(assume the two lines above are separated by quite a bit of code)

I have two conflicting type annotations here, but the compiler picks one and says it should be that type, but doesn't tell me where in the ast that comes from. It would be great if it said, "based on inference of usage at file:line:char", or "based on explicit annotation at file:line:char", so I could track down how it arrived at that conclusion and fix it much more quickly.

**Comment by jordwalke** [comment]
I wonder if that level of detail (the "why" not just the "what") would be possible by tapping into the general error printing (that's how Merlin prints in Reason syntax btw - we would just do the same for the regular ocaml compiler). If not, then it would need a change deeper in the type inference algorithm, and is something we could possibly get done and upstreamed into ocaml core compiler.

**Comment by anmonteiro** [comment]
this is upstream of reason
