### ISSUE TITLE
Clarify LICENSE in opam file.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#1285]

**Comment by jordwalke** [comment]
There's some automated opam tools (like Yarn has) that tell you which licenses your transitive dependencies have. For most people, just knowing the project is licensed as a BSD variant is sufficient, but other people would like to be informed that there is an additional grant of patent rights, so if opam allows it, we can include some kind of asterisk or link to more information.

**Comment by dbuenzli** [comment]
> For most people, just knowing the project is licensed as a BSD variant is sufficient,

Nobody like legalese, but please try to be a bit more professional: 

1. There's currently *nothing* that tells in the current metadata you provide that you are facing a BSD variant.
2. Just knowing that it's a BSD "variant" is absolutely not sufficient, if you add terms these are equally important to whatever license you claim you abide to. 

> there is an additional grant of patent rights

I would like to encourage you to actually try to read and understand the terms of termination of this "grant" of patent rights. You may then understand why this is important.

**Comment by dbuenzli** [comment]
Forgot to add here's a [suggestion](https://github.com/ocaml/opam-repository/pull/9376#discussion_r119758903) to move on.

**Comment by jordwalke** [comment]
> > "For most people, just knowing the project is licensed as a BSD variant is sufficient"

> Nobody likes legalese, but please try to be a bit more professional:

I'm not sure what you are referring to. Perhaps there is a communication problem? I genuinely believe that most people would find it perfectly acceptable to see something like:

```
Legal:
   Licenses: BSD
   Additional: [Patent Grant](url)
```

We are happy to include something like this, and if anyone still objects to that, I can find an expert to help us come up with a better description.

> 1. There's currently nothing that tells in the current metadata you provide that you are facing a BSD variant.

That is correct, and it is why I have made this Issue in the first place - because I believe there should be something that provides the consumer with all the relevant information and perhaps a link to find out more.

> 2. Just knowing that it's a BSD "variant" is absolutely not sufficient, if you add terms these are equally important to whatever license you claim you abide to.

I am not a lawyer and won't claim to know the best way to describe a software system that is licensed under BSD where there are additional patent grants are also supplied.

Here is how Facebook's React project is described:

<img width="566" alt="screen shot 2017-06-01 at 8 29 20 pm" src="https://cloud.githubusercontent.com/assets/977348/26709971/881e8d5e-470b-11e7-92d8-c94647161995.png">

Within that limited understanding, I believe that listing the BSD licensing in addition to a link to the additional grant of patents should not only satisfy those who only care to know that the software is licensed under BSD but with some additional terms, but should also satisfy those who want to investigate exactly what is granted beyond BSD and where they can read the actual grant of patents. That is what my original description of this issue is stating. Is there anything that you disagree with?

**Comment by dbuenzli** [comment]
> Is there anything that you disagree with?

Except for the metadata fix which is important due to potential dependency pulling I don't see any point in disagreeing. 

However I'd just like to point out that if I was a user of your software I would feel mislead by this statement:

> For most people, just knowing the project is licensed as a BSD variant is sufficient, but other people would like to be informed that there is an additional grant of patent rights

The patent grant adds a broad termination provision to the base BSD license which *in my eyes* doesn't make it a BSD license at all anymore.

**Comment by jordwalke** [comment]
> However I'd just like to point out that if I was a user of your software I would feel mislead by this statement:
>
> >For most people, just knowing the project is licensed as a BSD variant is sufficient, but other people would like to be informed that there is an additional grant of patent rights

I have no intention or desire to mislead. That statement is based on what I have observed to be a major use case for transitive dependency license reporting. Many people care just as much or more about making sure they don't link against any dependency that has a certain and particular license which they've found to be problematic for their circumstances, as they are about understanding the intricacies of *every* license of every dependency they pull in. They're both valid use cases, and my proposal recognizes this and accounts for both.

**Comment by StevenLangbroek** [comment]
@jordwalke are there plans to move this to MIT, like React? Or are the considerations different here. I'm evaluating compile-to-js languages for a product that falls under the ASF, so I can't use BSD+Patents components. It's no big deal, I'm just curious what the plans are so I can base my decisions on facts rather than FUD as we've seen in the last couple of months.

**Comment by jordwalke** [comment]
Stay tuned, @StevenLangbroek !

**Comment by anmonteiro** [comment]
Pretty sure this is done now that we generate Opam files from dune
