### ISSUE TITLE
Syntax proposal `guard let`

### ISSUE THREAD

**Issue by jaredly** [reasonml/reason#1302]
A follow-up to #1301, swift has this other nice piece of sugar, `guard let`.
Here's what it might look like in reason
```
guard let Some(val) = something else { None };
// ...rest of the code
```
which translates to
```
switch something {
| Some(val) => {
  // ...rest of the code
}
| _ => None
}
```

More generally
```
guard let %pattern = %value else { %if_not_matched_expression };
%if_matched_expression
```
becomes
```
switch %value {
| %pattern => %if_matched_expression
| _ => %if_not_matched_expression
}
```

early returns can be super helpful for readability imo.

`ppx_let` does a similar kind of thing, albeit with somewhat more magic https://github.com/janestreet/ppx_let

**Comment by anmonteiro** [comment]
unlikely we'll do this
