### ISSUE TITLE
? sugar for option

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1345]
`type foo = ?int`

**Comment by hcarty** [comment]
Should the `?` be suffix to match the syntax for optional parameters?

**Comment by bassjacob** [comment]
is this worth the separation between option and all the other ADT's? the way it is now, option is a great introduction to how the type system works since a new user has to internalise it to use it, if that makes sense.

**Comment by jaredly** [comment]
this is discussed in more detail somewhere else
