### ISSUE TITLE
JSX for Format

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1349]
It's a huge shame that something as clever as Format is so unknown. I'm thinking we can add some familiar sugar to it so that people get over the barrier of "huh ok what the heck is @[" and just appreciate the functionalities.

Example:

```reason
<hov>
   hello
</hov>
```

This would desugar to `Format.fprintf "@[<hov>%s@]" "hello"`

The advantages of this is that we're not overloading string, which was a point of confusion because people really expect string to be string. Also, less cryptic syntax.

**Comment by anmonteiro** [comment]
this is not planned
