### ISSUE TITLE
Support for refutation cases in pattern matching

### ISSUE THREAD

**Issue by hcarty** [reasonml/reason#1350]
http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec238 -- see the subsection titled "Refutation cases and redundancy"

Something along the lines of:
```reason
switch x {
| A -> /* Handle this case */
| B -> /* Handle this case */
| _ -> . /* States (with a check by the type system) that this case isn't possible */
}
```

**Comment by glennsl** [comment]
Surprised to see that this still isn't supported. Are there any workaround for this? I've tried various forms of type annotations, but that doesn't seem to be sufficient. I guess I could either disable warning 8 or just convert the whole module implementation to OCaml.

**Comment by rdavison** [comment]
Been hitting this issue as well.  You could also disable warning 56.

```reason
type t(_) =
  | A : t(int);

[@warning "-56"];
let foo = (x: t(float)) =>
  switch(x) {
  | _ => assert(false)
  };
[@warning "+56"];
```
