### ISSUE TITLE
[feature] arg-less switch

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1351]
```re
switch {
 a > b => ..
 c  => ...
}
```

which is equivalent to 
```re
switch () {
() when a >b => ..
() when c => ..
}
```

**Comment by bassjacob** [comment]
what would be the reason to use this over if/else?

**Comment by chenglou** [comment]
That's kinda neat. Pushing people toward `switch` is nice. Though it seems to trigger `Warning 25: bad style, all clauses in this pattern-matching are guarded` which we don't suppress

**Comment by bobzhang** [comment]
You can do a syntax check that argless switch requires a default branch

**Comment by OvermindDL1** [comment]
In the erlang ecosystem this construct is known as `cond`, if you want a different name for it (although `switch` seems fine for it too if no ambiguities pop up).

**Comment by hcarty** [comment]
Could the syntax be something different to help avoid visual ambiguity and to emphasize that a catch-all case is not something to encourage in normal `switch expr { | case => ... }`uses?

Maybe:
```reason
switch if {
| a > b => ...
| c < d => ...
| else => ... /* "else" is a keyword so maybe safe to use here? */
}
```

It could desugar to `if`/`else`s or `switch` with a catch-all case replacing the `else` case.

**Comment by bsansouci** [comment]
Is if/else not good enough?
```
switch {
 a > b => ..
 c  => ...
}
```
vs
```
if (a > b) {
   ...
} else if (c) {
   ...
}
```
?

**Comment by chenglou** [comment]
`switch {` and `switch () {` won't be possible in master since it conflicts, I think. But this might work:

```reason
if {
| a > b => ..
| c  => ...
}
```

Or drop the brackets:

```reason
if
| a > b => ..
| c  => ...
```

**Comment by anmonteiro** [comment]
I actually much prefer if this would be in `if` rather than `switch`, so personally I think it's a good thing that it's a conflict :)
