### ISSUE TITLE
Shouldn't these inlined docs use Reason syntax?

### ISSUE THREAD

**Issue by desmond-dsouza** [reasonml/reason#1352]
https://reasonml.github.io/api/Map.html

**Comment by chenglou** [comment]
Yes, though that's much harder; they're written in ocamldoc comments. cc @jsdf. Not sure what to do here

**Comment by jsdf** [comment]
I'm sure this can be fixed by just tweaking the build script a little. I'll take a look when I get a minute

**Comment by chenglou** [comment]
Related, there's https://reasonml.github.io/api/type_Map.html which isn't formatted correctly but isn't an inline doc
