### ISSUE TITLE
Real World Reason 

### ISSUE THREAD

**Issue by ShalokShalom** [reasonml/reason#1356]
I like to convert the OCaml reference "Real World OCaml" with refmt into a Real World Reason, meaning that all the examples get automatically transcompiled into Reason. 

And is there anything else to consider? Any news? Other changes? Its from 2013, so some things might have happen in the meanwhile, is anybody aware of it?

**Comment by bassjacob** [comment]
I believe there is already an effort underway both to modernise Real World OCaml and to offer it with Reason syntax.

**Comment by ShalokShalom** [comment]
Where can I find more info about it?

**Comment by gandulio** [comment]
WIP second edition is here: http://dev.realworldocaml.org

**Comment by avsm** [comment]
We'll be open sourcing the book repository soon along with the tooling, so I'll post on https://discuss.ocaml.org when that happens. Contributions such as Reason support are very welcome.

**Comment by avsm** [comment]
A good point of contact for Reason support is @SanderSpies, as he is working on some of the tooling around RWOv2

**Comment by ShalokShalom** [comment]
Thanks a lot

**Comment by ShalokShalom** [comment]
So, is it with pure Reason, pure OCaml or both?

**Comment by ShalokShalom** [comment]
@avsm Is there any blocker for the release?

**Comment by jordwalke** [comment]
@shalokshalom yes it should be that easy. But the question is, will RWO'a license allow this?

**Comment by ShalokShalom** [comment]
which licence is it?

**Comment by SanderSpies** [comment]
It will be OSS soonish, the focus currently is on OCaml though. If people
are interested in helping with Reason support, a good place would be the
ocaml-gist tool that I'm working on. It works with the Reason parser but I
haven't had time to actually add it.

If you are interested in helping with this ping me on Discord.

**Comment by ShalokShalom** [comment]
I am a no coder and thought simply putting it into refmt is enough.

**Comment by ShalokShalom** [comment]
Is there any news?

**Comment by jordwalke** [comment]
I believe the main issue is still RWO’s license prohibiting modification of the text.

**Comment by Huxpro** [comment]
Hey folks. I was experimenting on this: https://real-world-reason.gitbook.io/book/

I just completed the [chapter-2](https://real-world-reason.gitbook.io/book/chapter-2.-variables-and-functions) to see how it works out. 

The main difficulties for the converting are
1. Samples in RWO uses Jane Street's libraries (Core.std etc), Reason have very different standard libraries (`Js` and `Belt` and `Pervasive`), simply `refmt` is far from decent. Sometimes I need to tweak or come out a new sample to provide the same knowledge.
2. Samples in RWO are demonstrated with utop to provide an interactive education experience, while rtop has issues accessing `Js` and `Belt` and replay request `Js.log` (also it can not log data structure in the Reason form), so my conversion was mixing the usage of rtop and replay, which is awkward in many cases. 
Both made the conversion much more time-consuming than I thought.

The main conversion strategy was to **Keep "Real World OCaml" text untouched in any case** but take advantage of Gitbook's style to provide Reason hints and Reason code in Tabs (so you can switch between OCaml and Reason) Here is the [conversion guide](https://real-world-reason.gitbook.io/book/meta/conversion-guide) so ppl can contribute it.

**Comment by avsm** [comment]
Great work! I don't think there's a license issue if this is upstreamed eventually. cc @samoht @yminsky.

1) Seems to be a big blocker. Is the `Base` library supported from Reason JS?  If so, most of the v2 Guided Tour should be compatible. I'm not familiar with `Belt`, but I assume `Js` is the standard library for JavaScript, and `Pervasive` is the same as the OCaml one.

What's the advantage of GitBook _vs_ normal HTML output? Should we adopt Gitbook for RWOv2 as well rather than maintaining our own HTML output?

**Comment by jaredly** [comment]
Gitbook is a more streamlined experience, but I expect it would be harder (or maybe impossible?) to get ocaml code blocks to work the way you want.

**Comment by ShalokShalom** [comment]
Gitbook offers out of the box support for dark displayed content

**Comment by avsm** [comment]
I think we want to take the online RWO/RWR site more in the direction of an interactive notebook, so it's probably better for us to generate the HTML... if anything, heading towards a Juypter style might be best, as we already have both client- and server- side rendering for that (in OCaml anyway -- I imagine a Reason Jupyter notebook is pretty straightforward)

**Comment by Huxpro** [comment]
@avsm glad to hear!
As Jared said, Gitbook is more streamlined thus easier for the early experimenting purpose. But it's definitely very limited. Do we have any idea how to bake RWR into [RWO dev](https://github.com/realworldocaml/book)? 

In terms of heading towards a Juypter-like style,
<http://blog.klipse.tech/ocaml/2017/10/05/blog-ocaml.html>
<http://blog.klipse.tech/reason/2017/10/06/blog-reason.html>
maybe worth to look at.

**Comment by avsm** [comment]
We've been porting the RWO toolchain to use all the modern stuff - perhaps the first thing to do is to fork https://github.com/realworldocaml/book and generate a server-side formatting of Reason code (and add the tab option in).  That won't help with the standard library issue, but it will at least get the formatting right.

We've been thinking about how to add more community-generated chapters into the online version, so this is all heading in the right direction.  In fact, I wanted a JavaScript chapter in the main book for v2...

**Comment by jordwalke** [comment]
@avsm The license of RWO seems to present one issue.

**Comment by Huxpro** [comment]
Here is an update to the difficutlies I mentioned:

1. I am glad I am wrong with this. [jbuilder(dune)](https://github.com/ocaml/dune) have supported `*.re` first class and linking `Core.std` works very well. I do have pp (refmt) version uncompaitble when switching back and forth between 4.02 and 4.06 to test `Base`. But it should works in theory. 
Now my main concern is that RWO might not help as much for people using Reason for Web as it does for OCaml if we simply `refmt` everything. But It's another story.

2. if we wanna go with all `Core/Base`, then making rtop support them or making utop support `.re` is a necessary.

**Comment by ShalokShalom** [comment]
A Juypter Notebook sounds super +1

**Comment by Huxpro** [comment]
I agreed. As far as I know, there have been several Juypter-like notebook
implementations around OCaml/Reason community.

**Comment by jordwalke** [comment]
https://sketch.sh is a great system. It's not quite in book form, but all the pieces are there.

**Comment by anmonteiro** [comment]
dont think we have the manpower for this
