### ISSUE TITLE
refmt: improve line wrapping of long function signatures

### ISSUE THREAD

**Issue by TheSpyder** [reasonml/reason#1369]
Here's a contrived example of what refmt produces when the signature is long, but not _really_ long:

```
module type Thing = {
  let internalFunction:
    int => bool => string => list int => list bool => list string => option int;
};
```

Instead, I'd like it to be:
```
module type Thing = {
  let internalFunction: int => bool => string => list int => list bool => list string => option int;
};
```

If the signature does get _really_ long, it wraps completely:
```
module type Thing = {
  let internalFunction:
    int =>
    bool =>
    string =>
    list int =>
    list bool =>
    list string =>
    option int =>
    option string =>
    option bool;
};
```

That's fine. What I don't like is the halfway two-line wrap; I'd rather have it go a bit beyond the desired line length than come out with the weird wrapping it does now. Please don't wrap this case at all unless it's going full multi line wrapping.

**Comment by hoichi** [comment]
For what it’s worth, I like the current output better.
