### ISSUE TITLE
refmt breaks å, ä, ö

### ISSUE THREAD

**Issue by ulrikstrid** [reasonml/reason#1384]
When writing the string `"Alingsås"` it will reformat it to `"Alings\195\165s"` and that doesn't look like it should in the application (react native).

Using reason-cli 1.13.7 on Linux with vscode as my editor.

**Comment by bloodyowl** [comment]
unicode doesn't work in double-quoted strings, you can use the `js` BuckleScript tag so that your string works like a JS one `{js|Alingsås|js}`

**Comment by ulrikstrid** [comment]
Okay, is this something that should work?
It's not a major problem as I should not hardcode that string in to my app, just wanted it to be noted as Americans might not run in to this issue.

**Comment by bloodyowl** [comment]
AFAIK it comes down to how OCaml works given its internal representation of strings

**Comment by Schmavery** [comment]
I'd imagine it could be related to https://github.com/facebook/reason/issues/1053, https://github.com/facebook/reason/issues/799
