### ISSUE TITLE
Indentation for local scope

### ISSUE THREAD

**Issue by ShalokShalom** [reasonml/reason#1389]
I think a lot of people get attracted by such an optional way in Reason.
Especially people like me, coming from F-Sharp.

Also, Python users might appreciate it. 
Optionally, of course. 

This software can help to implement: https://www.typerex.org/ocp-indent.html
Block building through indentation is the preferred method for a lot people for a couple of reasons.

**Comment by ShalokShalom** [comment]
Since there is now a ppx live update build in reason-vscode, someone might realize that one here. 

I appreciate it :smiley:  

https://twitter.com/jaredforsyth/status/1085947362692890625

**Comment by anmonteiro** [comment]
unclear what the ask is here.
