### ISSUE TITLE
Reason doesn't allow overloading of list syntax?

### ISSUE THREAD

**Issue by imeckler** [reasonml/reason#1400]
Not sure if this is due to the OCaml parser on the [try Reason page](https://reasonml.github.io/try) being old, but it seems Reason does not support the overloading of the list type constructors and list syntax.

For example the following OCaml code does not work on the "try Reason" page (as you can see [here](https://reasonml.github.io/try/?ocaml=C4TwDgpgBMULwCgpQD5QNoF0mqgCgC4CBKKAewDMoBLAO1gCoYcEAbCWADygJngwCMAbigAmEQGZMQA)).
```
type t =
  | []
  | (::) of int * t
  
let x : t = [1; 2; 3]
```

**Comment by bassjacob** [comment]
I think this is more that `::` is not a valid infix operator. For instance

```
type t 'a = Null | Cons ('a) (t 'a);

let (@:) a b => Cons a b;

let (x: t int) = Cons 1 (Cons 2 (Cons 3 Null));
let (y) = 1 @: Cons 2 (Cons 3 Null);
```

works fine.

https://reasonml.github.io/try/?reason=C4TwDgpgBMUOQEMoF4oDkCuAbLUA+UAwgPYB2AzlABSICU1sdA3AFAtYSxUACAXPUgBGKAHxEylIa3adqAD14woAS1LB6qEhSgBGalsoAmfRKgBmdNiy1arDlxAbdUPuO3GqB85Zy2gA

**Comment by bassjacob** [comment]
oh wait, sorry, were you asking specifically about overloading the existing list operators?

**Comment by imeckler** [comment]
Yep, the code as indicated above works fine in OCaml (I ran it on 4.04.1 but I believe it was added a bit earlier).

**Comment by bassjacob** [comment]
Ah, understood. That might be hitting the issue that Bucklescript (ocaml -> JS) only supports OCaml 4.02.3, and the (::) operator and precedence rules might not have been present there. It may well work with reason -> ocaml -> native, but just not targeting JS with bucklescript.

**Comment by cem2ran** [comment]
@chenglou Is this still unsupported?
