### ISSUE TITLE
Replace `fun { |...` (aka ocaml `function`) with just `{ |...`

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1405]
Inspired by @bobzhang's #1351

```reason
let f = fun {
| A => 1
}
```

```reason
let f = switch {
| A => 1
}
```

GENIUS

cc @jordwalke

**Edit**: this conflicts with master's parens-less switch syntax. Better proposal:

```
let f = {
| A => 1
}
```

**Comment by ckknight** [comment]
I've been wanting to use this pattern particularly like so:

```reason
gimmeSomeData()
|> switch {
   | None => "nah"
   | Some(x) => x
   }
```

**Comment by bobzhang** [comment]
@ckknight how is it different from
```re
switch (gimmeSomeData()){
  | None =>"nah"
  | Some (x) => x
}
```

**Comment by jordwalke** [comment]
Interesting proposal!
It does have a conflict with the paren-less switch argument. If parents were required then there would be no conflict.

**Comment by jordwalke** [comment]
You know, there may even be a way to avoid the switch keyword even!

**Comment by chenglou** [comment]
How

**Comment by jordwalke** [comment]
If you omit the switch keyword and just begin with `  { |`, then it can implicitly be a lambda that pattern matches.

**Comment by chenglou** [comment]
Ok, let's do it

**Comment by ckknight** [comment]
@bobzhang: There is no semantic difference in that example.

**Comment by yawaramin** [comment]
Would you still be able to do `{ pat => exp... }`? E.g. OCaml:

```ocaml
let optionIsEmpty = function Some _ -> false | _ -> true
```

Reason:

```reason
let optionIsEmpty = { Some _ => false | _ => true }
```

?

**Comment by jordwalke** [comment]
@yawaramin I don’t believe that would work - you would need a leading BAR to determine that it is a lambda switch vs some other sequence that happens to contain a lambda.

**Comment by bsansouci** [comment]
One concern would be that there’s an implicit function allocation happening. Not sure if that matters a lot though, just a thought.

**Comment by TheSpyder** [comment]
maybe it would be less confusing in SML expression style? This wouldn't help with anonymous functions though.

```
let f (A) => 1
  | f (B) => 2

**Comment by yawaramin** [comment]
@jordwalke ah, OK.

I actually do like Cheng Lou's original proposal of `switch {...}`, it may be slightly more verbose but more importantly it's consistent with the way people will already be using `switch` in Reason. Besides, `switch { Some _ => false | None => true }` is a bit more aesthetically pleasing than a leading bar 😊

**Comment by jordwalke** [comment]
@TheSpyder  You could perhaps fix the lambda scenario by doing:

```
let f =
  | (A) => 1
  | f (B) => 2;
```

There are some parsing issues with this though - such as when returning a multi-case lambda from a switch.

```reason
let result = switch foo {
   | None => | (A) => 1 | (B) => 2
   | Some x => 0
};
```

Is the `| (B) => 2` another switch match case or a case of the returned lambda. It requires some parenthesis to disambiguate. 

```
let result = switch foo {
   | None => (| (A) => 1 | (B) => 2)
   | Some x => 0
};
```

Maybe not such a big deal if this is a rare pattern? I don't think I've ever written code like that.

**Comment by jaredly** [comment]
I think having the `switch` keyword would make it more accessible to newcomers -- can't we just say "you can't have the switch argument be a bracketed block?"
So instead of
```
switch { soFancy } {
 | Thing => x
}
```
you'd have to do
```
switch ({ soFancy}) {
}
```

I can't imagine that's a huge drawback

**Comment by yawaramin** [comment]
Agree with Jared; alternatively the syntax rule for `switch`, `if`, etc. could be that their arguments need to be enclosed in parens. Then you have either `switch (arg) PAT-MATCH-BLOCK` or `switch PAT-MATCH-BLOCK`.

**Comment by jordwalke** [comment]
@jaredly Might that be a separate issue? What of the multi-match form of lambdas?

**Comment by TheSpyder** [comment]
Actually, when I teach SML to new JS programmers on my team they are way more comfortable with repeating the function name with pipes in expression form than `let f arg = case arg of...` style.

The problem with `let result = switch foo {` style is that in normal code that would imply `foo` comes from the parent scope. The point of this style, to me anyway, is that you don't give a name to the function argument.

Using it inside a switch would definitely require brackets as it does in regular ML, but isn't that already true of the existing `fun` style?

**Comment by jordwalke** [comment]
@TheSpyder I wouldn't recommend having the switch keyword represent a function for the reasons you suggested. There's a couple other proposals here that don't involve the switch keyword though.

**Comment by jordwalke** [comment]
I like:

```reason
let f = (A) => 1;
        | (B) => 2;
```

Better than 
```
let f = (A) => 1;
  | f = (B) => 2;
```

because it doesn't look like `f` is bound to two different things. The Haskell like syntax of:

```
let f (A) = 1
let f (B) = 2
```

makes more sense because f itself is never "equal" to two things. `f(A)`  is equal to something and `f(B)` is equal to something.

**Comment by TheSpyder** [comment]
I agree repeating f is weird, but I have seen JS programmers who preferred it even when I pointed out doing it with long function names makes the code harder to read. It's a small sample size, but interesting that they thought about pattern matching in that way.

Your example is just the current syntax with `fun` removed? I'm fine with that. Whether we add braces as in the original proposal I don't have much of an opinion about.

**Comment by jaredly** [comment]
I would vote that the lambda form be:
```
let f = switch {
  | A => 1
  | B => 2
}
```
^ Is this subtly different? It seems quite obviously different to me.

**Comment by jaredly** [comment]
As far as
```
let f =
  | (A) => 1
  | (B) => 2;
```
goes, I think it's more of a departure from our recent standardization than the anonymous switch would be.

**Comment by TheSpyder** [comment]
it's not about whether it's subtle, having `switch` generate a function seems like it would cause confusion.

I know SML style is a departure. I really only suggested it because I've seen JS programmers latch onto it.

**Comment by chenglou** [comment]
@TheSpyder not having the `switch` word would dispel the confusion, right? (Also, we won't have the switch word anyway because as said above, it creates conflict)

@jordwalke there's another argument for this. This is invalid:

```reason
fun
| A => b; c
| B => d
```

Because you need:

```reason
```reason
fun
| A => {b; c}
| B => d
```

You avoided that with switch thanks to braces. I think we should here too.

**Comment by ckknight** [comment]
In light of #1804, I'd like to propose

```re
switch (_) {
  | A => B
  | C => D
}
```

used like so:

```re
gimmeSomeData()
|> switch (_) {
   | None => "nah"
   | Some(x) => x
   }
```

It still retains `switch` as the primary way to do pattern matching, and is a nice corollary with the function call syntax that uses `_`. This behavior would only apply if just `_` were used, the pattern `switch (Some(_)) { ... }` would be invalid.

**Comment by phated** [comment]
Was there a ever consensus here?

**Comment by yunti** [comment]
Hmmm as a newcomer I've just been having fun ;) with this little corner of Reason (it definitely feels like a bit of a wart).  It's not really mentioned anywhere in the docs apart from the ocmal vs reason section. 
https://reasonml.github.io/docs/en/comparison-to-ocaml#single-argument-match-functions

Instinct makes me think to go with the switch options that @jaredly mentioned this would make it seem like an extension to the switch pattern matching elsewhere but it is definitely weird having the switch keyword represent a function.
Couldn't we just use an underscore with the standard arrow syntax so we get the benefit of needing to give a name to the function argument.

```ocaml
let f = (_) =>
    |None => "nah"
    |Some(x) => x
```
