### ISSUE TITLE
[ideas] introduce a simple adt type `enum`

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1416]
It is much easier to derive toString/compare/Ord etc  without any hack and rock solid.
Part of the reason I don't like ppx_deriving is that it always look not solid to me

**Comment by IwanKaramazow** [comment]
How would you see this implementation-wise?

**Comment by chenglou** [comment]
So payload-less variants? Wouldn't you be able to check that at ppx time instead of introducing enum?
