### ISSUE TITLE
Move off travis completely

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1439]
Afaik the only blocker for us to go full CircleCI is that our travis setup includes macOS.

This also helps decongest travis' facebook/ queue.

**Comment by siwatpru** [comment]
I'm looking into this 👍

**Comment by chenglou** [comment]
Is it even supported on CIrcleCI? https://discuss.circleci.com/t/os-x-macos-ios-support-on-circleci-2-0/16430

**Comment by chenglou** [comment]
Oh wait, I think it is now?

**Comment by chenglou** [comment]
cc @dwwoelfel do you know if this is possible now?

**Comment by dwwoelfel** [comment]
I think this is possible by just adding another job that uses the macos container instead of a docker images: https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions

Should be fairly easy to test, but I'm not sure if I'll have time to get to it in the near future.
