### ISSUE TITLE
Switch syntax and string literal clash

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#149]
`switch bla {| a => b}` clashes with `{|hello new string literal ()()|}`.

The suggestion is to switch the string literal from {|a|} to `a` (a-la js) or maybe """ a-la python.

If we go with the former, we need to change polymorphic variant's syntax from `Bla to something else, like #bla.

**Comment by anmonteiro** [comment]
I think with Reason v3 this is no longer true? i.e. `switch` now requires parens.
