### ISSUE TITLE
Turn unit `()` into `.`

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1530]
The new syntax overloads parens a lot, and things like `foo(bar, baz, ())` are rather jarring. I'm wondering if we can instead replace it with `foo(bar, baz, .)`. This way we can also remove quite a few hard-coded rules for unit sugar, like `| Some () => ...`.

So it'd look like `foo(bar, baz, .)`. Likewise for declaration.

Disadvantage: not sure what `foo()` would look like. `foo(.)` looks weird. Maybe we can keep the `foo()` sugar.

**Comment by hcarty** [comment]
Also: `Ok()`

**Comment by ckknight** [comment]
I'd prefer if we can keep unary function call and constructor call as `func()` and `Thing()` respectively, perhaps truly representing `func(.)` and `Thing(.)` which could just `refmt` back into the former. Then, it's effectively just syntactic sugar for the real thing, which previously would have been `func(())`.

**Comment by gyzerok** [comment]
Why not just use word `unit`? 😉
