### ISSUE TITLE
[proposal] array access

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1579]
I think there is no ambiguity with the new paren syntax

```js
x[i] (* array access i *)
x["method"] (* instead of  x##method *)
x["method"] = "y"
```
Edit:  added an assignment

**Comment by hcarty** [comment]
Would this cause problems when the work on type-based disambiguation for `.()` lands in OCaml?

**Comment by bloodyowl** [comment]
@bobzhang don't you think it'd be confusing in letting users think they can pass a string literal?

**Comment by jordwalke** [comment]
@hcarty can you link to that upcoming feature? `.()` is hard to search for.

**Comment by hcarty** [comment]
@jordwalke https://github.com/ocaml/ocaml/pull/616 is the latest iteration I think.

**Comment by IwanKaramazow** [comment]
What keeps us from going the `x."method"` way?

Seems more consistent `{"stringKey": val}` & resembles method access from most other languages.

**Comment by bobzhang** [comment]
@IwanKaramazow it is more consistent with JS property access?

**Comment by bsansouci** [comment]
@bobzhang I think Iwan’s proposal might be less misleading than yours in the sense that people won’t be tempted to try `obj[key] = 10`
Then again we can also have a good error message and see if we actually make that mistake or not.

**Comment by IwanKaramazow** [comment]
I found a PR written by @SanderSpies which implemented the `x."method"` sugar. 
Apparently it broke editor highlighting, so it was delayed until the highlighting was fixed...

`x["method"]` is indeed more consistent with property access. But when people reach for this kind of code-style it's always for a key, not a method.
