### ISSUE TITLE
Odd case of removed AST portions.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#158]
When formatting the AST, everything after the first unit `()` is removed strangely (I believe it's the special casing of unit in the pretty printer that doesn't consider that it might be a function that is applied). It's lower priority because this is invalid code, but when formatting in the editor, we almost always have invalid code!

``` rust
  switch (nuclideOCamlPathToMerlin, nuclideOCamlPathToMerlinOverwrite) {
    | (_, Empty) => ()
        Atom.Config.set
          "nuclide.nuclide-ocaml.nuclideReasonOverwroteYour_pathToMerlin" nuclideOCamlPathToMerlin
    | _ =>()
  };
```

**Comment by anmonteiro** [comment]
no longer the case after syntax v3
