### ISSUE TITLE
refmt code style more neat for big module signature

### ISSUE THREAD

**Issue by huihui** [reasonml/reason#1606]
For big module signature, current refmt code style is something like

module MMMMMM:
__Reducer with type input_element = IIIIIIIII with
____type output_element = OOOOOOOOO with
____type configuration = CCCCCCCC = {
......
}

Can you improve it a little bit to something more nit like 

module MMMMMM: Reducer 
____with type input_element = IIIIIIIII 
____with type output_element = OOOOOOOOO
____with type configuration = CCCCCCCC = {
......
}

or

module MMMMMM: 
____Reducer 
____with type input_element = IIIIIIIII 
____with type output_element = OOOOOOOOO
____with type configuration = CCCCCCCC = {
......
}

**Comment by anmonteiro** [comment]
```reason
module MMMMMM:
  Reducer with
    type input_element = i and
    type output_element = u and
    type configuration = o;
```
