### ISSUE TITLE
Be more lenient about function requiring braces

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1683]
```reason
ReasonReact.SideEffects(
  (self) =>
    foo;
    bar
)
```

I think when it's unambiguous that `bar` is following `foo` in the function body, we should parse `bar` as part of the function body and add braces in printing.

cc @jordwalke @IwanKaramazow

**Comment by jordwalke** [comment]
My thought was that it would be kind of nice for the edit-time experience of extending the new callback formatting feature.

```reason
ReasonReact.SideEffects(arg, self =>
   self + self
);
```

You could easily add a line above the infix return value of the callback.

```reason
ReasonReact.SideEffects(arg, self =>
   let tmp = 0;
   self + self + tmp;
);
```
And then `refmt` would print the braces.

**Comment by jordwalke** [comment]
I think it would just require that in the parser when parsing `expression:`, we create a separate rule for expressions that are known to be in parameter position - and then relax the parsing rules a bit. Maybe not worth it if it's too invasive, tbph, but if it's easy we could consider it.

**Comment by chenglou** [comment]
We will never recommend nor document this feature; just that newcomers run into this a lot

**Comment by jaredly** [comment]
Automatic CurlyBrace Insertion :P
I could see that being helpful for people learning.
Might be nice to separate it out from the main syntax though -- have it be a "recovery" mode that gets done by the editor or something.
