### ISSUE TITLE
[refmt] Newline after leading BuckleScript attributes

### ISSUE THREAD

**Issue by brentvatne** [reasonml/reason#1702]
I personally find it more readable and clear to have leading attributes on their own line, eg:

```reason
[@bs.val]
external pi : float = "Math.PI";
```

However, this doesn't generalize too well, for example with `%bs.raw`

```reason
let timesTwo: int => int = [%bs.raw {|
  function(x) { return x * 2; }
|}];
```

Not a very high priority issue, but I thought I'd create an issue to give people a place to discuss this and weigh in on preferences and options.

**Comment by ubsan** [comment]
I don't use bucklescript (I program for native), but I do find that putting attributes on their own lines looks nicer to my eyes. For stuff like `%bs.raw`, that feels more like a kind of expression, as opposed to an attribute on an external.

**Comment by chenglou** [comment]
It does generalize, in the sense that @ and % are different. The latter doesn't have a problem. We do break line the way you suggest for the former, when the line's too long. Leaving this open in case folks want every such attribute to break line (_that_ might not generalize well. @ is used for other things than just bucklescript externals)
