### ISSUE TITLE
Improve option monad

### ISSUE THREAD

**Issue by haskellcamargo** [reasonml/reason#1710]
OCaml supports the `option` monad with a lot more functions than reason does, such as `join` as `>>=` and the possibility to deal with default values. What about making Reason implementation more similar to OCaml and Haskell (and also exposing `return`)?

```hs
(>>=) :: Monad m => m a (a -> m b) -> m b
```
This is what I'm doing right now to support compositional programming better:

![image](https://user-images.githubusercontent.com/7553006/34065105-f11385ce-e1e5-11e7-925a-99ef5112d453.png)

Also, as long as it can also be an applicative functor, support `map`/`fmap` would help a lot on point-free programming and avoid boilerplate.

**Comment by renatobenks** [comment]
@haskellcamargo please, share with your helpers to `Some`, `None` and `Maybe`, please!

**Comment by ubsan** [comment]
I'd prefer to call it `pure` - `return` is mostly a weird thing from early haskell, while `pure` comes from `Functor`.
