### ISSUE TITLE
Slightly confusing first-run experience

### ISSUE THREAD

**Issue by chriskrycho** [reasonml/reason#1729]
I've just installed Reason and, following the instructions, ran the default setup commands:

```
bsb -init my-first-app -theme basic-reason
```

I also followed the editor setup instructions to a 'T'.

Then I opened the project in VS Code, and was greeted immediately with an error:

![error](https://user-images.githubusercontent.com/2403023/34464899-870bf52a-ee52-11e7-85e0-2849d7a76643.png)

I'm excited about Reason, but that's a bad first look! 😬 The code you generate for a user should always work right out of the gate.

I'm sure I can sort this out in short order (this is not my first rodeo!), but figured I'd flag this up as a developer experience thing I imagine you all want to improve.

(If this is a duplicate or is already on your radar in some way, feel free to close, of course!)

**Comment by chriskrycho** [comment]
Found the explanation: it's [here](https://reasonml.github.io/guide/editor-tools/global-installation#editor-error-message-unbound-module-js-etc) in the setup docs.

It's really easy to miss because it comes *before* the guide covers actually installing the VS Code extension.

It'd also be great if the VS Code extension didn't have to be at the root of the repo for this stuff to work – combined/multi-language projects in a single repo are a thing!

**Comment by jordwalke** [comment]
I’ve found that much of VSCode relies on opening the proper project root. It really does help achieve the “just works” developer experience. With the upcoming multiroot workspaces feature it should improve the kinds of workflows you mentioned.

**Comment by chriskrycho** [comment]
@jordwalke yeah, I just ran into a nearly identical problem with the Rust extension. Happy to close if you like; moving (or repeating?) the note in the docs is probably the most actionable takeaway I can think of here, since it's a limitation of the editor.

**Comment by jordwalke** [comment]
We can keep it open until the docs are improved (PRs always welcomed)
