### ISSUE TITLE
Built in syntax for async.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#173]
I've really liked `Lwt`'s syntax for async (including the integration with `try`, `let`, and `let` + `and` for simultaneously async calls). We can bake this into Reason by default with something like `let!`, and then allow configuration of which library it should represent.

Imagine putting an attribute at the top of the file such as:

```
[@async Lwt];
```

or

```
[@async Async];
```

which could influence which library is used for that first class let binding syntax.

For the implementation, we could reuse `Lwt`'s `ppx` plugin perhaps.

**Comment by bolinfest** [comment]
I'm probably missing some context here, but if `!` means what I think it means, how would you express the following (which is valid using Babel/regenerator in JavaScript today) in Reason:

```
async function(): Promise<void> {
  if (await someCall()) {
    const [first, second] = Promise.all([thisReturnsAPromise(), thisAlsoReturnsAPromise()]);
  }
}
```

I believe there was a proposal to add syntactic sugar for `Promise.all()` that died, which would have allowed for something like:

```
async function(): Promise<void> {
  if (await someCall()) {
    const [first, second] = await* thisReturnsAPromise(), thisAlsoReturnsAPromise();
  }
}
```

**Comment by wiltonlazary** [comment]
i think that with my proposal, async can be an ordinary suspendable function.
No need to create more syntax, since internal DSLs assembles language itself.
https://github.com/facebook/reason/issues/1982

```
let myAsyncFunc = async {
  body
};
```

**Comment by wiltonlazary** [comment]
i think that with my proposal, async can be an ordinary suspendable function.
No need to create more syntax, since internal DSLs assembles language itself using functions.
https://github.com/facebook/reason/issues/1982

```
let myAsyncFunc = async {
  body
};
```

**Comment by wiltonlazary** [comment]
No need to reinvent the wheel, some languages already have the battle tested solution to this.

https://github.com/facebook/reason/issues/864 internal DSLs + coroutines "aka suspendable functions".

**Comment by wiltonlazary** [comment]
No need to reinvent the wheel, some languages already have the battle tested solution to this.

https://github.com/facebook/reason/issues/1982 internal DSLs + coroutines "aka suspendable functions".

**Comment by anmonteiro** [comment]
`let` binding opts now cover this use case. and we can define `let.async` etc
