### ISSUE TITLE
Flip list and array syntax to increase JavaScript-familiarity

### ISSUE THREAD

**Issue by aaronshaf** [reasonml/reason#1759]
If the array syntax was:

```
[1, 2, 3]
```

And the list syntax was:

```
[|1, 2, 3|]
```

... I wonder if that would aide in onboarding JS devs? It seems like arrays will be much more used anyway.

**Comment by ubsan** [comment]
IME, lists are far more useful in OCaml, because you can't change the size of arrays.

**Comment by cullophid** [comment]
Immutability is a really important concept in reason. Lists are immtable which is why they are chosen over arrays.

**Comment by thangngoc89** [comment]
Array is only used more when compiling to JS, list is more useful in OCaml.

**Comment by anmonteiro** [comment]
Not gonna do this
