### ISSUE TITLE
RFC: nicer javascript external syntax

### ISSUE THREAD

**Issue by jaredly** [reasonml/reason#1788]
The current method of adding bs decorators to the c-style `externals` declaration leaves a lot to be desired, and it's clearly a shoehorn effort.
What would it look like to have first-class support for defining javascript externals?

Here are my current thoughts, expressed in the form of potential PPX syntax (for testing). We could upgrade it to parser-level support later.
```
import {a, b} from "./ab.js";
// instead of
[@bs.module "./ab.js"] external a: someType = "";
[@bs.module "./ab.js"] external b: someOtherType = "";
[@bs.module "./ab.js"] external renamed: someOtherType = "c";
// we could have
[@from "./ab.js] [%external_import: {.
  a: someType,
  b: someOtherType,
  [@name "c"] renamed: someOtherType,
}];

import someDefault from "someLibrary";
// instead of
[@bs.module] external someDefault: someType = "someLibrary";
// we could have
let someDefault = [@from "someLibrary"] [%external_import: someType];
```

Aaand then there's the issue of defining external functions for operating on javascript objects, which I think is a much more complicated problem.
Here's what I've been thinking of doing:
```
[%external_object
type  firestore = {
  enablePersistence: unit => Js.Promise.t(unit),
  collection: string => collection('t),
  app: unit => firebase,
}]

// would translate to
type firestore;
[@bs.send] external enablePersistence: firestore => Js.Promise.t(unit) = "";
[@bs.send] external collection: firestore => string => collection('t) = "";
[@bs.send] external app: firestore => firebase = "";
```

**Comment by jordwalke** [comment]
So some of the syntactic suggestions happening here could also apply to non-external, and even C externs?

**Comment by ncthbrt** [comment]
Not so sure about `[%external_import: someType]`
I quite like how externals are currently analogous to let bindings. Would much prefer something along these lines (not sure how possible this is):
`external someDefault: someType = [@from "someLibrary"];`

**Comment by jaredly** [comment]
@jordwalke it's true, but OCaml's current extern syntax is similar to the one used in C itself.

@ncthbrt it's a balance of which language you privilege :D this proposal makes "importing from javascript" look more similar to javascript than OCaml. I think that's a decent place to fall to, given that the "import from C" (external) syntax looks like C.

**Comment by anmonteiro** [comment]
Externals need a comprehensive proposal that targets all idioms and can be tried in userland first
