### ISSUE TITLE
Some(tuple) is two args in the online playground

### ISSUE THREAD

**Issue by xtuc** [reasonml/reason#1791]
Repro: [playground](https://reasonml.github.io/en/try.html?reason=MoewtgpgFFCMA0sCUSg). The option should have the type: `option((int, int))`.

It works in rtop and with my own function:

```reason
let f = (a) => a;
f((1,1));
```

**Comment by jaredly** [comment]
It works in [the new playground](https://reason.surge.sh/?syntax=Reason&code=DYUwLgBAHhC8EGUD2BbEAKdBGANFglPkA&canvas=200) that we'll be switching to soon.
