### ISSUE TITLE
Allow "naming" function args in signatures.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#1805]
In signatures, it would be nice to name unnamed args just for documentation purposes:

```
let x : (firstArg : int, secondArg : string) => int;
```

**Comment by andreypopp** [comment]
Would be a bit confusing as there are named args too, no?

I wonder if not having this would make people tend to use named args more. I think it's a nice pattern to have a single (or two at max) position arg and others — named.

**Comment by jordwalke** [comment]
Yes, but sometimes named args aren't practical for things like higher ordered functions. Some things will not type check.

**Comment by IwanKaramazow** [comment]
If they aren't part of the ast, how can refmt print them?

**Comment by jordwalke** [comment]
@IwanKaramazow We can make them be part of the AST by parsing them into PPX attributes.
