### ISSUE TITLE
Unexpected behavior calling a function with positioned arguments that accepts labeled parameters 

### ISSUE THREAD

**Issue by nikgraf** [reasonml/reason#1837]
Today I ran into a situation I don't understand:

```
let name = (~forename, ~surname) => forename ++ " " ++ surname;
```

Calling the function like this was expected:

```
name(~forename="Jane", ~surname="Doe");
name(~forename="Jane")(~surname="Doe");
```

I was surprised to see that the function can also be invoked with positional arguments:
```
name("Jane", "Doe");
name("Jane")("Doe");
```

Even this works fine:
```
let nameWithForename = name(~forename="Jane");
nameWithForename("Doe");
```

But when executing this snipped:

```
name(~forename="Jane")("Doe");
```

I receive the following error:
```
Error: The function applied to this argument has type
         (~surname: string) => string
This argument cannot be applied without label
```

This was totally unexpected. As @mrnonrespondo in Discord pointed out is that this doesn't throw an error:
```
(name(~forename="Jane"))("Doe");
```

This resulted in two question:
1. Is this intentional and if yes how would you explain it.
2. What are the benefits of allowing labeled parameters to invoked with positional arguments?

**Comment by bsansouci** [comment]
It seems to be that your error comes from mixing named and positional arguments in the same call. 
You can't do `name(~forename="Jane", "Doe");` but you can assign the result of the partial application `name(~forename="Jane")` to a variable that you then call with positional arguments. 

Allowing functions with labelled arguments to be called without their arguments is part of the semantics of ocaml, so probably not something Reason will change any time soon. The benefits are for higher order functions, like passing `let myFunc = (~name) => ...` to `Array.map(myFunc, myArray)` for example.
Personally I use named arguments as a way to document the purpose of the arguments that is better than comments, and being able to pass them positionally is a nice shorthand to have sometimes.

**Comment by bsansouci** [comment]
I'm not sure what you're asking anymore.

`unit` argument at the end isn't required but you can imagine that if you have 2 optional arguments and you only pass the first one, OCaml can't tell if you want it to fully evaluate the function call using the default value for the 2nd argument or partially apply and wait for the 2nd argument to be provided.
We advise using `unit` at the end because that helps OCaml understand when you mean to fully apply (when you add the `()`) or when you mean to partially apply (when you omit the `()`).

Does that make sense?

**Comment by mimshwright** [comment]
This one was especially weird to me...
```
name(~forename="Jane")("Doe"); /* Error */
(name(~forename="Jane"))("Doe"); /* Ok */
```
but after looking at the compiled ocaml, I could see how it would be difficult to disambiguate this.

**Comment by jaredly** [comment]
There's a warning defined for "applying a function without the label" (https://caml.inria.fr/pub/docs/manual-ocaml/native.html, warning 6). You can turn that into an error if you want to avoid the confusion (with the `"warnings"` configuration item in the bsconfig).
