### ISSUE TITLE
Better syntax error for `return foo`

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1845]
Something like "`return` doesn't exist in Reason; blabla"

**Comment by ubsan** [comment]
What if someone names a function `return`, as with monads (although that's a terrible name, it's still used)

**Comment by bsansouci** [comment]
We could make it a hint, like we’ve done in the past. The hints are 100% accurate but they help give some idea of what caused the problem. Like “did you miss a semicolon” etc

**Comment by chenglou** [comment]
`return foo` is invalid syntax, not a function

**Comment by mrkaspa** [comment]
Reason does not need something like this :/

**Comment by chenglou** [comment]
Folks, please read the title. It's to provide better syntax error message when people attempt to do `return foo`, which is invalid in reason. Right now the error message is `<UNKNOWN SYNTAX ERROR>`
