### ISSUE TITLE
turn strings into quoted strings

### ISSUE THREAD

**Issue by TheSpyder** [reasonml/reason#1870]
This might be an interesting way to help with unicode support.

Translate a normal string in reason:
`let str = "世界"`

Into the quoted version of ocaml:
`let str = {|世界|}`

Or `{js|` if you prefer (both work for me, never really known what the difference is)

**Comment by IwanKaramazow** [comment]
It's fixed in master: https://github.com/facebook/reason/pull/1838

**Comment by TheSpyder** [comment]
hmm. It's cool that string contents aren't escaped anymore, but according to my read of the bucklescript docs without `{js| |js}` they'll still be escaped in the final JS output?

https://bucklescript.github.io/docs/en/interop-cheatsheet.html#string-unicode-interpolation

https://bucklescript.github.io/bucklescript/Manual.html#_bucklescript_annotations_for_unicode_and_js_ffi_support

**Comment by jaredly** [comment]
Yup that's true ([playground example](https://reason.surge.sh/?syntax=Reason&code=DYUwLgBA9gdiEF4ICJBocoGVdkG4BQpJgDuUiEA3gFYDOAPhjdQL5ZA&canvas=200))
I wonder if the bucklescript repo is the right place for this? seems like it would be nice for all strings to be un-escaped.
