### ISSUE TITLE
A sugar for function application ending with unit?

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1877]
suppose we have a function whose type is
```ocaml
val f :  ?a0:int -> a1: int -> ?a2:int -> unit -> t  
```
In most cases, you dont want an accidential currying happens(see https://github.com/BuckleScript/bucklescript/issues/2670), you would write

```ocaml
f ~a1:3 ()
```

I imagine if in reason, we can have a small sugar like this

```re
f(~a1=3 .)
```

Some random thoughts, not of high priority

**Comment by jordwalke** [comment]
I have a larger proposal that goes even further and doesn’t require the dot.
