### ISSUE TITLE
[ideas] provide a sugar for writing deprecations

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1881]
currently if we want to deprecate something, we need

```ocaml
val oldAPI : ty1 -> ty2 -> ty
[@@ocaml.deprecated "use newAPI instead] 
val newAPI: ty1 -> ty2 -> ty
```

I wonder whether reason could provide a sugar so that 
```ocaml
val oldAPI as newAPI : ty1 -> ty2 -> ty
```
Inspired by this issue: https://github.com/BuckleScript/bucklescript/issues/2675

When  we deprecate one name in a lot of modules, it is easy to miss one or two

**Comment by ckknight** [comment]
I often deprecate a function and replace it with one with different arguments, that wouldn't work in this case, would it? This seems to be for simple renames.
