### ISSUE TITLE
[Syntax] Semicolon rules confusing

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#191]
This could go on and on so I'll only file one issue for it. I'll collect all the confusing parts of semicolon here.
- In a switch/catch block there shouldn't be a semicolon like this:

```
switch x {
| a => 5;
}
```
- In a local open, there shouldn't be one:

```
MyModule.(bla;)
```
- Braces not followed by semi:

```
let f => blablabla
let a = 5;
```

```
if (true) {
  ...
}
let a = 5;
```

And this is a bit nuanced, formatting this will succeed by with the wrong result (f slurped inside else block):

```
if (true) {a} else {b}
f ();
```

**Comment by mrkaspa** [comment]
It will be good to have ASI or remove the semicolons from the language and have the return keyword may be

**Comment by anmonteiro** [comment]
no longer relevant after semicolon recovery
