### ISSUE TITLE
Annotation on recursive type kinda weird

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1918]
```reason
type user = {..}
[@bs.deriving abstract]
and t = user;
```

The deriving annotation is on `t`. Maybe this is more intuitive?

```reason
type user = {..}
and [@bs.deriving abstract] t = user;
```

Though maybe not really since for consistency the regular type declaration would need to be:

```reason
type [@bs.deriving abstract] user = {..}
```

**Comment by jaredly** [comment]
yeah I think the current way makes sense 🤷‍♀️
