### ISSUE TITLE
Documentation errors? Bigarray, Num, Unix, etc.

### ISSUE THREAD

**Issue by mchaver** [reasonml/reason#1931]
There are some links to some modules that don't seem to exist in reason/BuckleScript like Bigarray, Num, Unix. These don't seem to actually exist in either language or am I missing something?
https://reasonml.github.io/api/index.html

**Comment by bsansouci** [comment]
We should be clear inside the Reason docs that these modules aren’t supported by bucklescript yet. 
Could you add this to the list of documentation issues here https://reasonml.chat/t/about-documentation-immutability-first-class-functions-and-dynamic-and-static-environments/594 we’ll fix them very soon.

**Comment by anmonteiro** [comment]
Reason is not just about compiling to JS
