### ISSUE TITLE
Destructuring records/objects into function labels 

### ISSUE THREAD

**Issue by Risto-Stevcev** [reasonml/reason#1933]
Something like this would be convenient:

```reason
type foo = {bar: string, baz: int};
let z = {bar:"blah", baz:123};
let f = (~bar, ~baz) => bar;

/* be able to apply arguments like this:
 * (I think this would need some special syntax to disambiguate):
 */
f(z);

/* which would be equivalent to: */
f(~bar: z.bar, ~baz: z.baz);
```

and to have the same for JS objects like `{. "bar": ... }`

**Comment by jaredly** [comment]
hmmm unfortunately, this goes beyond what can be done simply at the parser (AST) level, as it requires knowledge of the types (in this case, the type of `f`). I think this is probably out of scope --- @chenglou comment?
