### ISSUE TITLE
Syntax Proposal: function coercion "is the key to internal DSLs".

### ISSUE THREAD

**Issue by wiltonlazary** [reasonml/reason#1982]
When a function receives a parameter that is a function, allow it to coerce with this form:
Obs: its allow languages to have constructions that assembles language itself using functions.

object block:
{.}
{..}

record block:
{,} 

executable block:
{;}

function block:
{}

//Obs: self enclosed function block form ex:  {it => "xx"} or {(it)=>"xx"} | {=>} or {()=>} or {}

let ext1 = (self: string, block: unit=>string) => {
  self ++ "xxxx";
};

let ext2 = (self: string, block: string=>string) => {
  block(self ++ "xxxx");
};

/*actual form*/
ext1("x") (()=>{"xx"}); 

/*coerced new form*/
ext1("x") {"xx"}; 

/*actual form*/
ext2 ("x") ((arg0)=>{"xx"}); 

/*coerced new form*/
ext2 ("x") {it => "xx"}; 

-----------------------------------------------------------
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like i said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

some(2, 3) {
  body
};
/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3) () => {
  body
}  () => {
  body
}; 

/*or like actually valid*/
some(2, 3) (() => {
  body
}) ( () => {
  body
}); 
```

**Comment by jaredly** [comment]
kotlin has this, swift has this... might be interesting to try out to see how it would effect real-world codebases. I'm a little skeptical, as it's one more thing to be confused by when learning a syntax, but I understand it can be nice.

**Comment by wiltonlazary** [comment]
It is not because of kotlin, internal DSLs in my humble opinion, open a lot of opportunities and ReasonML is realy near with this small and not intrusive addition, self enclosed function blocks "{it => "xx"}" instead of "it=>{"xx"}" make alot of sense in conjunction with all others self delimited blocks like objects,records and so.

**Comment by wiltonlazary** [comment]
object block:
{.}
{..}

record block:
{,}

function block:
{=>}

**Comment by jaredly** [comment]
Hrmm `{a => b; c}` currently means "two expressions, the function `a => b`, and then the value `c`. Changing it to mean "a function with two expressions, b and c" feels like way too big of a jump.

**Comment by wiltonlazary** [comment]
I' m looking forward to see if it will impact on deployed code base, but this syntax make real sense with the rest of blocks on the language.

**Comment by wiltonlazary** [comment]
I wonder if you or someone agree that self contained blocks make sense for functions, if some one have a suggestion for that.

**Comment by wiltonlazary** [comment]
Maybe semicolon on the end be promoted to resolve it.

function: 
    {a => b; c}

executable block:
    {a => b; c;}

**Comment by wiltonlazary** [comment]
Maybe semicolon "the sequencer operator" on the end be promoted to resolve it.

function:
{a => b; c}

unit function block "can scare someone ;)":
{}

executable block:
{a => b; c;}

unit executable block example:
{;}

Syntax highlight can recognize and make this beautiful

**Comment by wiltonlazary** [comment]
Maybe semicolon "the sequencer operator" be promoted to resolve it.

function:
{a => b; c}

unit function block "can scare someone ;)":
{}

executable block:
{;a => b; c}

unit executable block example:
{;}

Syntax highlight can recognize and make this beautiful

**Comment by wiltonlazary** [comment]
I think that in functional language, function syntax is the queen.

**Comment by wiltonlazary** [comment]
Maybe semicolon "the sequencer operator" be promoted to resolve it.

function:
{a => b; c}

{a => 
  b; 
  c
}

unit function block "can scare someone ;)":
{}

executable block:
{;a => b; c}

{;
  a => b; 
  c
}

unit executable block example:
{;}

Syntax highlight can recognize and make this beautiful

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient form internal DSLs becouse assembles a language construct itself.

<code>
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};
</code>

other("fn") {(arg)=>
  body
};

Instead of:

<code>
some(2, 3) () => {
  body
};

other("fn") (arg) => {
  body
};
</code>

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient form internal DSLs becouse assembles a language construct itself.

`
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};
`

other("fn") {(arg)=>
  body
};

Instead of:

`
<code>
some(2, 3) () => {
  body
};

other("fn") (arg) => {
  body
};
`

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient to form internal DSLs, because assembles a language construct itself only using functions.

`
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};

other("fn") {(arg)=>
  body
};
`

Instead of:

`
some(2, 3) () => {
  body
};

other("fn") (arg) => {
  body
};
`

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like i said, this is the secret ingredient to form internal DSLs, because assembles a language construct itself only using functions.

`
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};

other("fn") {(arg)=>
  body
};
`

Instead of:

`
some(2, 3) () => {
  body
};

other("fn") (arg) => {
  body
};
`

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient form internal DSLs becouse assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};

other("fn") {(arg)=>
  body
};

/*You can even use this to create builder form:*/

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3) () => {
  body
};

other("fn") (arg) => {
  body
};
```

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};

other("fn") {(arg)=>
  body
};

/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3) () => {
  body
};

other("fn") (arg) => {
  body
};
```

**Comment by wiltonlazary** [comment]
I think that internal DSLs is the last frontier to make ReasonML an universal replacement to any language, even over Ruby,Kotlin,Groovy,Scala and so on.

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

other("fn") {arg =>
  body
};

other("fn") {(arg)=>
  body
};

/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3)  () => {
  body
}  () => {
  body
}; 
```

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

some(2, 3) {
  body
};
/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3) () => {
  body
}  () => {
  body
}; 
```

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like a said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

some(2, 3) {
  body
};
/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3) () => {
  body
}  () => {
  body
}; 

/*or like actually valid*/
some(2, 3) (() => {
  body
}) ( () => {
  body
}); 
```

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like i said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

some(2, 3) {
  body
};
/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
Instead of:

 
some(2, 3) () => {
  body
}  () => {
  body
}; 

/*or like actually valid*/
some(2, 3) (() => {
  body
}) ( () => {
  body
});

**Comment by wiltonlazary** [comment]
I think that is easy to parse and mentally homogeneous this form, since it clearly make blocks self contained, and like i said, this is the secret ingredient to form internal DSLs because assembles a language construct itself.

```
some(2, 3) {=>
  body
};

some(2, 3) {() =>
  body
};

some(2, 3) {
  body
};
/*You can even use this to create builder forms of high order functions, from function that receives functions as parameters */

some(2, 3) {
  body
} {
  body
};
```

Instead of:
```
 
some(2, 3) () => {
  body
}  () => {
  body
}; 

/*or like actually valid*/
some(2, 3) (() => {
  body
}) ( () => {
  body
}); 
```

**Comment by jaredly** [comment]
hmmm I'm not seeing how making this syntax change would allow us to implement async/await in userland. Could you elaborate here?

**Comment by wiltonlazary** [comment]
implement suspendable functions instead of keywords async/await.

internal DSL it will make possible to create syntax constructions only with functions.
when "suspendable function" "aka coroutine" exists it will be possible without change language syntax.

instead of create a concept of async/await let it be functions.
async will be a function of the core library and await will be a suspendable function of the core library.
i can make a suspendable function by my self.

suspendable functions can be called in context of others suspendable functions.

it will delegate the responsibility of suspension to the leaf most call and free the caller to worry about asynchronous detail, but someone can wait on a promise since i can have a suspendable function that receive a promisse.

**Comment by wiltonlazary** [comment]
implement suspendable functions instead of keywords async/await.

internal DSL it will make possible to create syntax constructions only with functions.
when "suspendable function" "aka coroutine" exists it will be possible without change language syntax.

instead of create a concept of async/await let it be functions.
async will be a function of the core library and await will be a suspendable function of the core library.
i can make a suspendable function by my self.

suspendable functions can be called in context of others suspendable functions.

it will delegate the responsibility of suspension to the leaf most call and free the caller to not worry about asynchronous detail, but someone can wait on a promise since i can have a suspendable function that receive a promisse.

**Comment by wiltonlazary** [comment]
implement suspendable functions instead of keywords async/await.

internal DSL it will make possible to create syntax constructions only with functions.
when "suspendable function" "aka coroutine" exists it will be possible without change language syntax.

instead of create a concept of async/await let it be functions.
async will be a function of the core library and await will be a suspendable function of the core library.
i can make a suspendable function by my self.

suspendable functions can be called in context of others suspendable functions.

it will delegate the responsibility of suspension to the leaf most call and free the caller to not worry about asynchronous detail, but someone can wait on a promise since i can have a suspendable function that receive a promise.

**Comment by wiltonlazary** [comment]
implement suspendable functions instead of keywords async/await.

internal DSL will make possible to create syntax constructions only with functions.
when "suspendable function" "aka coroutine" exists it will be possible without change language syntax.

instead of create a concept of async/await let it be functions.
async will be a function of the core library and await will be a suspendable function of the core library.
i can make a suspendable function by my self.

suspendable functions can be called in context of others suspendable functions.

it will delegate the responsibility of suspension to the leaf most call and free the caller to not worry about asynchronous detail, but someone can wait on a promise since i can have a suspendable function that receive a promise.

**Comment by wiltonlazary** [comment]
Actualy i use, suspendable functions to releave my co-workers from create bugs when forget to call await, no more awaits every where and when nessesary they can interact with promise calling await or other espetialized suspendable function can be used to do the job.

**Comment by wiltonlazary** [comment]
Actualy i use, suspendable functions to releave my co-workers from create bugs when forget to call await, no more awaits every where and when nessesary they can interact with promise calling await or other suspendable function can be used to do the job.

**Comment by wiltonlazary** [comment]
implement suspendable functions instead of keywords async/await.

internal DSL will make possible to create syntax constructions only with functions.
when "suspendable function" "aka coroutine" exists it will be possible without change language syntax.

instead of create a concept of async/await let it be functions.
async will be a function of the core library and await will be a suspendable function of the core library.
i can make a suspendable function by my self.

suspendable functions can be called in context of others suspendable functions.

it will delegate the responsibility of suspension to the leaf most call and free the caller to not worry about asynchronous detail, but someone can wait on a promise since i can have a suspendable function that receive a promise.

Who call the core library function suspend(callback(continuation)) is the actual "suspensor" of the computation, and it continues when the callback calls "continuation.resume()".

**Comment by wiltonlazary** [comment]
I know that i'm referencing the Kotlin coroutine framework that enables all kind of async computations, and DSLs are part of that language too.

I'm not bring the language here, but only the concept that is already battle tested and is not new to computation folks "continuations" and "DSLs".

**Comment by wiltonlazary** [comment]
Actualy i use, suspendable functions to releave my co-workers from create bugs when they forget to call await, no more awaits every where and when nessesary they can interact with promise calling await or other suspendable function can be used to do the job.

**Comment by jaredly** [comment]
"adding suspendible functions to the language" isn't really on the table right now -- if you're interested, check out the "algebraic effects for ocaml" work that's being done. It's very promising, but probably a couple years out before it lands. It's not really a trivial "oh just add this to the runtime" kind of a thing 😅

As for this syntax change, I'm still pretty skeptical of it. We already dramatically changed the look & feel of function blocks, and that time it was in service of being more familiar to folks coming from javascript. This would actively work against that, and I'm not convinced that it would offer a ton of benefit.
If we had a concrete example of a codebase that would be made much simpler / easier to write/maintain etc. by this change, then that would be a useful way to further the conversation.

**Comment by jaredly** [comment]
btw I definitely don't want to come off as raining on your parade -- I can tell you're excited about this, and that's what we need for this community to thrive! I'm just cautious about introducing sweeping syntax changes -- there's a very real cost to a change like this, and I want to make sure the benefit is worth it.

**Comment by wiltonlazary** [comment]
The only change that is not compatible with current Syntax are ";" at begin of executable blocks, the rest can stay to keep javascript people happy and function coercion will be a plus.

I'm very glad to be part of this and i'm trying to bring my opinion to prevent this great effort to become like Dart.

In 2011 i participated on a debate almost like that, on Dart forum, folks of Dart say the same thing about  not make peple familiar with Java upset.

In my opinion, people that are happy with javascript will not adopt a new paradigm language only for  syntax familiarity, people that are unhappy or feel limited by the mess of javascript will be open to small syntax changes to bring then great future prof implementations, internal DSLs are a ruge advantage to language syntax.

My sincere admiration to you be patient with my argumentation, thank you ;)

**Comment by wiltonlazary** [comment]
**The only change that is not compatible with current syntax is ";" at begin of executable blocks**, the rest can stay to keep javascript people happy and function coercion will be a plus.

I'm very glad to be part of this and i'm trying to bring my opinion to prevent this great effort to become like Dart.

In 2011 i participated on a debate almost like that, on Dart forum, folks of Dart say the same thing about not make peple familiar with Java upset.

In my opinion, people that are happy with javascript will not adopt a new paradigm language only for syntax familiarity, people that are unhappy or feel limited by the mess of javascript will be open to small syntax changes to bring then great future prof implementations, internal DSLs are a ruge advantage to language syntax.

My sincere admiration to you be patient with my argumentation, thank you ;)

**Comment by wiltonlazary** [comment]
I'm studying PPX rewriters and encountered a corner case that self contained function block simplify.
When someone annotate a block without enclose with more parenthesis, in fact is annotating only the parameter.


```
let myFunc = [@cps] {it =>
      it ++ string_of_int(1);
      "xxx";
};

let myFunc =  {[@cps] it =>
      it ++ string_of_int(1);
      "xxx";
};

/*instead of*/

let myFunc = [@cps] it => {
      it ++ string_of_int(1);
      "xxx";
};

let myFunc = [@cps] (it => {
      it ++ string_of_int(1);
      "xxx";
});
```

**Comment by jaredly** [comment]
hmm it looks like
```
let myFunc = [@cps] it => {
      it ++ string_of_int(1);
      "xxx";
};
```
puts the annotation on the function expression, not the argument. If you want to annotate the parameter, this will do it
```
let myFunc = ([@cps] it) => {
      it ++ string_of_int(1);
      "xxx";
};
```
(tested locally with Refmt 3.1.1)

**Comment by wiltonlazary** [comment]
The problem seems be only shifted, people will need think about wrap to disambiguate the syntax.

**Comment by wiltonlazary** [comment]
```
 <Button
                 onPress=(
                   () =>{ 
                         log(1) ;
                         log(2);
                      }
                 )
                 title="Press"
               />
/* VS */
 <Button
                 onPress={ 
                         log(1);
                         log(2);
                 }
                 title="Press"
               />
```
