### ISSUE TITLE
Error messages for poly variant syntax error are hard to understand

### ISSUE THREAD

**Issue by arnarthor** [reasonml/reason#1994]
```ocaml
type apiKeyError
   = [|`Dev |`Prod];
type validationErrors = [ | `AnalyticsPlatformMissing | `ApiKeyMissing(apiKeyError)];
```

This just gives a generic kinda cryptic syntax error message with no context and my editor (Emacs) pointed me to the later type decleration (CLI did point to the correct line). 
As soon as I change it to ```[ |`Dev |`Prod]``` it reformats just fine.

Wondering if it's possible to detect something like this since it's probably quite common due to the similarities with array and poly variant declaration.

**Comment by hcarty** [comment]
This is more forward looking, but there are/may be plans to add custom array types to the core language.  See https://github.com/ocaml/ocaml/pull/616.  That shouldn't hold this particular issue up!  Just a note that there may be a real use for `type = [| ... |];` as a syntax in the future.
