### ISSUE TITLE
Coroutine/Continuation/Async/Await PPX already operational.

### ISSUE THREAD

**Issue by wiltonlazary** [reasonml/reason#2018]
https://github.com/wiltonlazary/cps_ppx

Hi guys, for me asynchronous computations are a matter of urgency, then I made a PPX that behind scene transform discret sequential code into AST continuation, for simple code style as an act to prove the viability and get helped to implement all the AST patterns.

if more people get on board, it can move further, i have only 20 days on ReasonML but i think that the code is ok for a proposal.

```
What works fully async by now:
------>    nested [@cps] function declaration
------>    function apply "named by: await/delay or with sufix Cps/Await/Delay"
------>    single let bindings
------>    if/then/else
------>    match/cases
------>    try/cases

What will come fully async on short:
------>    context api
------>    channels
------>    for/while loops
------>    instance methods on cps apply detection
------>    ...
```

**Comment by anmonteiro** [comment]
binding ops work now
