### ISSUE TITLE
AST Visualizer plugin (Forked/Inspired from TypeScript's) [LOWPRI]

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#205]
It might be fairly easy to repurpose the typescript visualizer for the Reason AST. Thiw would help us debug the parser, but would also be a good chance for users to explore the syntax - we can include small explanations about language features.
https://github.com/TypeStrong/atom-typescript#ast-visualizer

**Comment by anmonteiro** [comment]
Ast explorer has reason support
