### ISSUE TITLE
Add OCaml Version flag for OPrinter tests

### ISSUE THREAD

**Issue by ryyppy** [reasonml/reason#2107]
There is an issue with the test system where new syntax breaks the tests for older OCaml versions.
We need to copy the OCaml version logic from the other testers (currently implemented in bash) to the JavaScript based Oprinter tester.

**Failing PR with inline record syntax (4.04):**
https://github.com/facebook/reason/pull/2103

**CI Error:**

```
Fatal error: exception File "./TestTest.ml", line 1, characters 10-12: inline records are not supported before OCaml 4.03
```
See: https://travis-ci.org/facebook/reason/jobs/410926463#L2552

**Comment by reynir** [comment]
One way could be to to put the minimum required OCaml version in the file name. Then one could write (in a test runner implemented in OCaml!):
```OCaml
if Sys.ocaml_version ^ ".re" >= String.sub source_file (String.length source_file - 9) 9
then call_outcome_printer source_file
else ()
```

**Comment by anmonteiro** [comment]
tests are running on cram now
