### ISSUE TITLE
[Printing] Ternary are not very readable

### ISSUE THREAD

**Issue by danielo515** [reasonml/reason#2160]
Hello,

Sadly refmt is not configurable, I can live with most of the already taken decisions, but I really think the default (and only!) configuration should favor readability.
There is a particular case with ternaries that makes them almost invisible on big portions of JSX.
For example, compare this where the ternary sections are clearly visible:
![captura de pantalla 2018-08-26 a las 11 02 48](https://user-images.githubusercontent.com/2270425/44626862-8334ea00-a924-11e8-96b8-cd94958666ce.png)

With this one, where there is almost impossible to spot where the ternary starts and where does it ends:

![captura de pantalla 2018-08-26 a las 11 02 14](https://user-images.githubusercontent.com/2270425/44626879-c000e100-a924-11e8-807a-3c862c98368a.png)

I asked about this on discord and @IwanKaramazow asked me to ping him on this issue, so here it is

**Comment by davesnx** [comment]
This should be fixed after #2294
