### ISSUE TITLE
[refmt] ocamldoc (**/**) stop comment can't be written

### ISSUE THREAD

**Issue by leostera** [reasonml/reason#2178]
**Input (OCaml)**
```ocaml
(**/**)
```

**Reformats to (Reason)**
```reason
/***/**/
```

Which doesn't compile back into `(**/**)` and thus can't be used.

**Alternative Input (Reason)**
```reason
[@ocaml.doc "*/*"]
```

**Compiles to (OCaml)**

```ocaml
[@@@ocaml.doc (("*/*")[@reason.raw_literal "*/*"])]
```

**And reformats back to (Reason)**
```reason
/***/**/
```

Which doesn't compile back into `(**/**)` and thus can't be used. 🤯 😆 

**Expected behavior**

Some comment translates to `[@ocaml.doc "*/*"]` without breaking the syntax. Right now I can't seem to be able to get it there.

**Comment by anmonteiro** [comment]
Duplicate if #1923
