### ISSUE TITLE
Inconsistent parsing/printing for default values in type declarations/annotations.

### ISSUE THREAD

**Issue by cristianoc** [reasonml/reason#2230]
https://reasonml.github.io/en/try?rrjsx=true&reason=DYUwLgBAZgXBAUA-Axge2KgTnAzmTAlgHYDmAvAPwA0ExYAlBGQHy1GRkBQECK6WcVAAcwBVEXh5CpepRoAPRiwjyIAaggBGANycgA

This is the way to type the following function currently:
```reason
let foo: (~color: string=?, int) => int =
  (~color: option(string)=?, x) => x + 1;
```
The type annotation on the whole `foo`, and the named argument `color`, refer to the same type, yet only the latter uses `option`.

The ocaml version, without punning, is still a bit confusing, but one can see what's going on:
```ocaml
let f: ?color:string -> int -> int =
  fun ?color:(color : string option)  -> fun x  -> x + 1
```

**Comment by IwanKaramazow** [comment]
![image](https://user-images.githubusercontent.com/10634678/46928527-4e4b3680-d03b-11e8-9549-1b3e07f9c336.png)
For some reason the constraint on the pattern is ignored and formatted as a constraint on the expression instead. I'm investigating.

**Comment by jordwalke** [comment]
I sketched an explanation of this [here](https://sketch.sh/s/qOJ6mx4EqFV9pw8YfzOxjL/).
Open to ideas about potential syntactic improvements.
