### ISSUE TITLE
Add support for JVM as a target

### ISSUE THREAD

**Issue by behrangsa** [reasonml/reason#2252]
TL;DR: what the title says.

---
TS;TMM (too short, tell me more):

Similar to Scala and Kotlin, it would be nice if ReasonML was available on JVM too -- even only if via GraalVM.

While .NET has F#, if I am not wrong, there are not any popular ML-based languages available on JVM.

[OCaml-Java](http://www.ocamljava.org/) might be a good starting point: maybe you can invite its developers to join Reason and help you with targeting JVM.

**Comment by midnio** [comment]
As I remember, OCamlJava was official. That would be good. Implementing should be easy too because reason compiles into OCaml, just give OCaml code to OCamlJava compiler.

**Comment by davesnx** [comment]
Because OCamljava exists, there's already a way to target JVM.

Closing this, sorry for the ping of and old issue.
