### ISSUE TITLE
Code editor on try page is broken

### ISSUE THREAD

**Issue by thetilliwilli** [reasonml/reason#2257]
Code editor on the page [https://reasonml.github.io/en/try](https://reasonml.github.io/en/try) is broken when i paste this code
```
1t
```
here is the permanent link for issue [https://reasonml.github.io/en/try?rrjsx=true&reason=IwFyA](https://reasonml.github.io/en/try?rrjsx=true&reason=IwFyA)

errors in a console
![image](https://user-images.githubusercontent.com/25109940/48305217-d556d600-e537-11e8-8f12-b7422b7a1c88.png)

my web browser
Google Chrome
Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by anmonteiro** [comment]
This has been replaced by the melange playground
