### ISSUE TITLE
rtop doesn't work properly on windows

### ISSUE THREAD

**Issue by andreypopp** [reasonml/reason#2261]
After #2167 rtop runs on Windows but there's a problem with it — the shell seems to not pass the control over stdin/stdout to the rtop command and input/output is interleaved between the shell and the rtop program.

Repro:
```
% npm install -g esy@0.4.0
% git clone https://github.com/andreypopp/hello-reason
% cd hello-reason
% git checkout rtop-on-windows
% git submodule init # bring reason repo
% git submodule update
% esy
% esy utop # works!
% esy rtop # launches but doesn't work
```
 
I tested this with `cmd.exe` own terminal and `ConEmu` running `cmd.exe`.

cc @ulrikstrid as you worked on fixing #2167

**Comment by anmonteiro** [comment]
Please reopen if there’s still an issue. The windows tests for rtop seem to be passing
