### ISSUE TITLE
New compiler warning for expressions containing multiple calls to functions with side-effects

### ISSUE THREAD

**Issue by joelonsql** [reasonml/reason#2266]
The order of evaluation of arguments is explicitly undefined in OCaml.
http://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sec129
> The order in which the expressions expr, argument1, …, argumentn are evaluated is not specified.

This means it's possible to get different results for the same expression,
if the expression contains multiple calls to functions with side-effects.

Here is an example where I managed to shoot myself in the foot due to this recently:

```reasonml
let foo = (a, b) => {
    print_string(string_of_int(a) ++ " " ++ string_of_int(b));
};
let x = ref(0);
let bar = () => {
  x := x^ + 1;
  x^
};
foo(bar(), bar());
```

This produces different output when run in `rtop` compared to running the Bucklescript-generated .js code in Node or the browser:

```
$ node src/Demo.bs.js
1 2
$ rtop
Reason # foo(bar(), bar());
2 1- : unit = ()
```

It is currently the developer's responsibility to be aware of `bar()`'s side-effects,
and to fix the problem by explicitly force the order of evaluation using temporaries:

```reasonml
let a = bar();
let b = bar();
foo(a, b);
```

What I would like very much as a developer, is a warning from the compiler for code like `foo(bar(), bar())`, explaining to me that since `bar()` has side-effects and the expression contains multiple function calls, the order of evaluation could cause different results.

I understand this is a non-trivial compiler warning to develop, but given the importance for me, I would be willing to financially contribute to such a project, if the maintainers also think such a compiler warning would be a good idea.

Discussion: https://reasonml.chat/t/reasonml-evaluation-order-gotcha/1222

Bounty: https://www.bountysource.com/issues/66336949-new-compiler-warning-for-expressions-containing-multiple-calls-to-functions-with-side-effects

**Comment by hcarty** [comment]
This may have to wait for/be coordinated with effect tracking to land in OCaml.

**Comment by anmonteiro** [comment]
Not planned for reason
