### ISSUE TITLE
Better syntax for js externals

### ISSUE THREAD

**Issue by aaronshaf** [reasonml/reason#2279]
Instead of:

```reason
[@bs.module] external foo: string => string = "bar";
```

I propose:

```reason
[@bs.module] external bar as foo: string => string;
```

That `"bar"` in the first is super confusing for beginners. Not intuitive.

**Comment by jordwalke** [comment]
Good idea. That particular proposal would require a concrete syntax change in reason in addition to requiring a BuckleScript ppx change. The following would only require a BuckleScript ppx change.

```
let foo: string => string = [%require "bar"];
```

Maybe that's just as intuitive?

**Comment by aaronshaf** [comment]
IMO, that last `=` is misleading, unfortunately. It looks like an assignment for the second `string`.

**Comment by aaronshaf** [comment]
Per [JustGate's tweet](https://twitter.com/JustGage/status/1068901153759420416), another suggestion:

```reason
[@bs.module] external foo: string => string from "bar";
```

Essentially replacing the `=` at the end with a `from`

**Comment by justgage** [comment]
I was actually thinking `import foo: string => string from "bar";` Or maybe `importJs foo: string => string from "bar";` Just make it as es6 as possible.

**Comment by justgage** [comment]
I do really like @jordwalke's syntax as well though, maybe even better 👍
