### ISSUE TITLE
Proper error when using unit in function type declaration

### ISSUE THREAD

**Issue by iddan** [reasonml/reason#2284]
I am relatively new to ReasonML, but coming from a rich FlowType background. I tried to do:
```reason
type a = () => string;
```
And received the cryptic error message in try Reason:
```
<syntax error>
``` 
And a proper syntax error message in Merlin (which was not useful as well)
I turned to the docs and discovered I should have done:
```reason
type a = unit => string;
```

**Comment by jaredly** [comment]
Yeahhh. imo it would be great to have the parser just accept `()` as an alias for `unit` in the type position
