### ISSUE TITLE
Windows - refmt: Globs are not expanded

### ISSUE THREAD

**Issue by bryphe** [reasonml/reason#2287]
__Platform:__ Windows 10. Reproduces in both `powershell` and `cmd`

__Issue:__ The glob format is not recognized when running refmt on Windows.

__Repro:__ Run the following command on any repo with reason files:
- `esy b refmt --in-place src/**/*.re`

__Expected:__ All files, including files in nested directories of `src`, should be formatted.
__Actual:__ Get an error message:
```
refmt: FILENAMES... arguments: no `src/**/*.re' file
Usage: refmt [OPTION]... [FILENAMES]...
Try `refmt --help' for more information.
```

It seems like based on #1748 , that we're relying on the shell to do the glob expansion, but this won't work on Windows - we'll have to expand that. It'd be helpful to have a `glob`-style or `minimatch`-style library to assist with this (maybe something that could be part of the reason-native utils?)

**Comment by jaredly** [comment]
Is it standard for windows cli tools to handle glob expansion for you?

**Comment by bryphe** [comment]
Hi @jaredly ,

> Is it standard for windows cli tools to handle glob expansion for you?

Yes, this is the standard practice. In the Node ecosystem - there are some popular modules that help out with this: [`glob`](https://www.npmjs.com/package/glob), [`globby`](https://www.npmjs.com/package/globby), and [`minimatch`](https://www.npmjs.com/package/minimatch) come to mind.

Some examples of CLI apps that leverage this strategy are:
- `prettier` - https://github.com/prettier/prettier/blob/e12cd17be2d80585d7b9fc9710e0fdbfd6bc3c2e/src/cli/util.js#L411
- `mocha` - https://github.com/mochajs/mocha/blob/f9a6f9b908c28d58b9e393b51a61f0216e8549e5/lib/utils.js#L517

It'd be helpful to have a native implementation of something like `glob` or `minimatch` - cc @jordwalke - perhaps an idea for the `reason-native` project?

**Comment by anmonteiro** [comment]
Glob expansion is a shell feature.
