### ISSUE TITLE
Refmt generating invalid output for functions that return first class modules in REI file

### ISSUE THREAD

**Issue by bordoley** [reasonml/reason#2295]
In my REI file I have:

```
let toValueLikeInstance: t('a) => (module RxValueLikeInstance.S with type a = 'a);
```

which refmt is formatting as:
```
let toValueLikeInstance:
  t('a) => (module RxValueLikeInstance.S) with type a = 'a;
```

which does not compile.

**Comment by anmonteiro** [comment]
This is not the case in master or even in `refmt` v3.3.7. Which version are you running?

**Comment by bordoley** [comment]
Let me sync up with @jordanwalke. I encountered this internally at Facebook. Not sure which version of bucklescript we currently depend on.

**Comment by davesnx** [comment]
Closing as a revolved old issue, sorry for the ping
