### ISSUE TITLE
[refmt] PPX inside switch

### ISSUE THREAD

**Issue by afxpsd** [reasonml/reason#2300]
Input:

```reason
let _ =
  x =>
    switch (x) {
    | `A =>
      [%log.debug "DbWroker::Init"];
      ();
    };
```

Output:

```reason
let _ =
  x =>
    switch (x) {
    | `A =>
      %log.debug
      "DbWroker::Init";
      ();
    };
```

**Comment by alexfedoseev** [comment]
Bumping this issue. Refmt messes `ppxlib` extensions badly:

```reason
[%expr
  switch (x) {
    | "" => 0
    | _ => 1
  }
]
```

becomes

```reason
switch%expr (x) {
| "" => 0
| _ => 1
};
```

There is no syntax error though.

**Comment by Lupus** [comment]
While it all works, and we can live with this, resulting code after formatting is very counter-intuitive especially with meta-quoting semantics when you want a clean separation between what's inside, and what's not.

**Comment by alexfedoseev** [comment]
FWIW in the initial case there is a syntax error, so this behavior breaks code.

**Comment by alexfedoseev** [comment]
> FWIW in the initial case there is a syntax error, so this behavior breaks code.
Hmm, I think something has changed and it doesn't break things anymore. Still this behavior is confusing imo, especially in context of `ppxlib`.

**Comment by hcarty** [comment]
There are no syntax errors because the resulting syntax is the sugared ppx form in each of the cases shown. The reason it doesn't break anything is because the two forms are equivalent at the AST level.

I don't have a link handy, but from what I recall there was a decision made a long while ago to have refmt put all ppx usage into the sugared syntax for consistency. I understand the concern, though, if the goal in your extension is to be visually explicit about the transformed scope.

**Comment by Lupus** [comment]
Refmt preserves original curly braces in some cases even if they are
redundant. May be same could be done for ppx.

Btw, by adding curly braces around ppx areas with meta-quoting I'm able to
mostly outline what's in, and what's out of spliced ast fragnents.

ср, 22 янв. 2020 г., 19:43 Hezekiah M. Carty <notifications@github.com>:

**Comment by alexfedoseev** [comment]
Here is the case when refmt breaks code:

Works: https://reasonml.github.io/try?rrjsx=true&reason=NoUgzgLgTglgUAAgQGwKYQQfQQXgQDwFoA+AMwHtyAKAQ12IVFQQEYBdASjjYG44g
Reformatted: https://reasonml.github.io/try?rrjsx=true&reason=NoUgzgLgTglgUAAgQGwKYQQfQQXkUhAD3yQFoA+AMwHtqAKAQ13JIKRFVbYEYuEBKOAF0A3HCA

**Comment by alexfedoseev** [comment]
Syntax error:

```reason
open Meta;
open Ast;
open AstHelpers;

open Ppxlib;
open Ast_helper;

let ast = (~loc, scheme: Scheme.t) => {
  [%stri
    let initialFieldsStatuses = (input: input): fieldsStatuses => [%e
      Exp.record(
        scheme
        |> List.map((entry: Scheme.entry) =>
             switch (entry) {
             | Field(field) => (
                 Lident(field.name) |> lid(~loc),
                 [%expr Pristine],
               )
             | Collection({collection, fields}) => (
                 Lident(collection.plural) |> lid(~loc),
                 [%expr
                   [%e collection.plural |> E.field(~of_="input", ~loc)]
                   ->Array.map(_ =>
                       %e
                       {
                         Exp.record(
                           fields
                           |> List.map((field: Scheme.field) =>
                                (
                                  Lident(field.name) |> lid(~loc),
                                  [%expr Pristine],
                                )
                              ),
                           None,
                         );
                       }
                     )
                 ],
               )
             }
           ),
        None,
      )
    ]
  ];
};
```

Works:

```reason
open Meta;
open Ast;
open AstHelpers;

open Ppxlib;
open Ast_helper;

let ast = (~loc, scheme: Scheme.t) => {
  [%stri
    let initialFieldsStatuses = (input: input): fieldsStatuses => [%e
      Exp.record(
        scheme
        |> List.map((entry: Scheme.entry) =>
             switch (entry) {
             | Field(field) => (
                 Lident(field.name) |> lid(~loc),
                 [%expr Pristine],
               )
             | Collection({collection, fields}) => (
                 Lident(collection.plural) |> lid(~loc),
                 [%expr
                   [%e collection.plural |> E.field(~of_="input", ~loc)]
                   ->Array.map(_ =>
                       [%e
                         {
                           Exp.record(
                             fields
                             |> List.map((field: Scheme.field) =>
                                  (
                                    Lident(field.name) |> lid(~loc),
                                    [%expr Pristine],
                                  )
                                ),
                             None,
                           );
                         }
                       ]
                     )
                 ],
               )
             }
           ),
        None,
      )
    ]
  ];
};
```

**Comment by davesnx** [comment]
Pretty old issue, but it's fixed in https://github.com/reasonml/reason/issues/2300
