### ISSUE TITLE
Outcome printer bug for inline records

### ISSUE THREAD

**Issue by hcarty** [reasonml/reason#2323]
From rtop:
```reason
Reason # type t = A {x:int};
type t = A();
```

I would have expected `A {x: int}` rather than `A()` from the REPL response.  The type definition still works as expected, it seems to be solely a printer issue.

**Comment by anmonteiro** [comment]
I think https://github.com/facebook/reason/pull/2103 fixes this, but someone that has signed the CLA might need to contribute a pull request with the same code.

**Comment by anmonteiro** [comment]
@hcarty it looks like you had even reported this in https://github.com/facebook/reason/issues/1163

**Comment by anmonteiro** [comment]
This was fixed in #2370
