### ISSUE TITLE
Inline record parsing for variants is more strict than expected

### ISSUE THREAD

**Issue by hcarty** [reasonml/reason#2324]
Reason usually errs on the side of consistent paren wrapping.  This doesn't hold for inline records in variants which is rather unexpected.  For example, this will parse:
```reason
type t = A {x: int};
```
but this will not:
```reason
type t = A({x: int});
```
The first version isn't bad, but the second version not parsing is pretty unexpected given how other variant constructor definitions work.

**Comment by anmonteiro** [comment]
both parse
