### ISSUE TITLE
How can I model disjoint unions in Reason?

### ISSUE THREAD

**Issue by talbenari1** [reasonml/reason#2328]
Let's say I have a JS library that I'd like to set up foreign interop for. One of the library's functions returns a value in one of the following forms:

- `{ success: true, value: {...} }`
- `{ success: false, error: {...} }`

In something like Flow, you could model this using [disjoint union types](https://flow.org/en/docs/types/unions/#toc-disjoint-unions). Is there a way to model this kind of type in Reason? Because I can't find any documentation on this on either the Reason website or the BuckleScript website.

**Comment by hcarty** [comment]
You probably want a [variant type](https://reasonml.github.io/docs/en/variant).

In the future, https://reasonml.chat/ and the Reason discord channel are probably better places to get answers to questions like this.  You're more likely to get a quick and complete answer on either of those than here on the issue tracker.
