### ISSUE TITLE
Recursive types. Unused BuckleScript attribute: bs.deriving

### ISSUE THREAD

**Issue by liubko** [reasonml/reason#2329]
at first issue was filled in [bucklescript repo](https://github.com/BuckleScript/bucklescript/issues/3299)

----

I'm getting this warning
```
Warning number 101
OCaml preview 2:55-65

Unused BuckleScript attribute: bs.deriving
```
when I'm trying to define a recursive type like this ([playground](https://reasonml.github.io/en/try.html?rrjsx=true&reason=NoAQRgzgdAJgpgJwJYDckDsDmACAhpAFwVwGMCBdAKAIE8AHObEgewBsBXAW3WwF5sA3pWzZQkKMzoEkzdLlZURmOAQAScXPAQAFBJIgAubMoK79AYXmswpANYAaSgF9KY6FtQYc+CEVIVKXHQYbDo9Ogg+QWEmNi50QzwEYhoAChYObgBKRxE3CSkZOQUYkzMIozLwiEtWaztHFyCQqosrGxJbKNSw-XtsSWlZdLjsrL4APmwAJQ0yABEAeQBZWaheiIBuSiA)):

_ocaml_
```
type column = {
  getHeaderProps: getPropsCallback[@bs.optional ];}[@@bs.deriving abstract]
and props =
  {
  columns: column array;
  getProps: getPropsCallback[@bs.optional ];}[@@bs.deriving abstract]
and getPropsCallback = props -> column option -> ReactDOMRe.props
```

I think the warning is misleading, please correct me if I'm wrong

**Comment by anmonteiro** [comment]
this is not a reason issue, but rather that the bucklescript / melange ppx only needs the last `@@deriving` in a `type / and` block. it's rather about the ppx implementation
