### ISSUE TITLE
docs issue: bsb-native link goes to an "old repository"

### ISSUE THREAD

**Issue by guidorice** [reasonml/reason#2332]
Hi, on this page https://reasonml.github.io/docs/en/native it says:

> Bsb-native is like our JS-side build tool, but that compiles to native code instead.

That link goes to `bsb-native`, which on it's github repo says
> Old repository. The code was moved in an actual fork of bucklescript

This is fairly confusing to a newcomer. Maybe the native page should just link to `esy`? If there are multiple ways to build native code with Reason, maybe they should be enumerated there as well.

I also read the  "Note: the native workflow is heavily work-in-progress." so feel free to close if this is a known issue.

**Comment by davesnx** [comment]
bsb-native has been discontinued a long time ago. Closing this.
