### ISSUE TITLE
Can't use unicode escape in native reason

### ISSUE THREAD

**Issue by saitonakamura** [reasonml/reason#2337]
I can't get how to use unicode escaping in reason
i'm writing `let oghamSpace = "\u{1680}";` looking at this PR https://github.com/ocaml/ocaml/pull/1232
but i'm getting `Warning 14: illegal backslash escape in string.`

**Comment by OvermindDL1** [comment]
What's your backing version of ocaml?  (`ocamlc -version` of whichever your reason toolline is calling)

As I recall it requires a minimum version of OCaml 4.06 (but it might have been 4.06.01 or 4.07?).

**Comment by anmonteiro** [comment]
@OvermindDL1 even if OCaml has support for it we need to actually implement it in the Reason lexer.

**Comment by hcarty** [comment]
I tested here on OCaml 4.07.1 + Reason 3.4.0.  `utop` accepts it without issue, but `rtop` gives the same warning @saitonakamura reported, so it does look like it's a missing feature in the Reason lexer.

**Comment by saitonakamura** [comment]
I stumbled upon this in [Revery package.json](https://github.com/revery-ui/revery/blob/master/package.json#L58), so it's looks like ocaml version is alright

**Comment by jordwalke** [comment]
Thanks for the report. @hcarty Do you know how to fix this in the Reason lexer? I think that's where this fix would go. And then it would get backported to all previous ocaml compiler versions automatically when using Reason.

**Comment by hcarty** [comment]
@jordwalke I think the https://github.com/ocaml/ocaml/pull/1232 PR's code could be reused almost directly.  I think using that code, though, would require someone with consortium license access to pull it in in order to keep things friendly with Reason's MIT license.

**Comment by anmonteiro** [comment]
fixed in https://github.com/reasonml/reason/pull/2738
