### ISSUE TITLE
Differentiate between `fn (.)` and `fn(.())`

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#2357]
Relevant: https://github.com/BuckleScript/bucklescript/issues/3429

Currently they are all de-sugared into OCaml syntax `fn () [@bs]`

The thing is that in BuckleScript, since there is no syntax space for arity zero, so we make a special form that `fn () [@bs]` is treated arity zero application.

I wonder Reason could make a difference here which feels more intuitive:

`fn (.)` --> arity zero -> `fn () [@bs]`
`fn (. ())` --> arity 1 -> `let unit = () in fn unit` of course, some care need to be taken to avoid name collision

**Comment by anmonteiro** [comment]
This would need to remain compatible with OCaml, and I don’t see a viable way to do that
