### ISSUE TITLE
Missing completions with merlin, possible parser recovery errors

### ISSUE THREAD

**Issue by hcarty** [reasonml/reason#2371]
Some examples:
- [ ] Module in an explicit top-level expression
```reason
module L = List;
let () = L.i/* No completion for L here, but adding a ; after the cursor allows completion to work */
```

- [ ] Module in an implicit top-level expression
```reason
module L = List;
L./* No completion for L here, trailing ; does not allow completion to work */
```

- [ ] Record field in a function definition
```reason
type t = {x: int};
let f = (v: t) => v./* No completion here, but adding a ; after the cursor allows completion to work */
```

- [ ] Top-level expression after comment?
```reason
let xyzza = "hello";
/* let foo = 0; */
xyz/* No completion here, works if the previous line is uncommented */
```

- [ ] Completing record fields in the middle of a function call
```reason
type t = {
  x: int,
  y: int,
};

let f = (v: t) => {
  print_int(v./* No completion here */);
};
```

Another one:(Added by jordwalke)

```
let extract = "hi";
let foo = 0;
switch(extra<CURSOR>) {
}
```
(But if you add one case to the switch body, then it will complete - I think this means we should just parse switch statements with zero cases, and let the compiler fail later.

**Comment by hcarty** [comment]
I'll add more as I find them.  Others are welcome to do the same!

**Comment by jordwalke** [comment]
Thanks for getting the ball rolling on this!

**Comment by jordwalke** [comment]
Another one that came up is when you try to add a new test case in a rely test that only has one existing test:

```
descripe("TestSuite", ({expect}) =>
  test("shoudlequalthree", ({expect}) => {
    expect.int(3).toEqual(3);
    expect.int(3).toEqual(3);
  })
);
```

It's very common for someone to try to add another test case:

```
descripe("TestSuite", ({expect}) =>
  test("shoudlequalthree", ({expect}) => {
    expect.int(3).toEqual(3);
  })
  test("shoudlequalthree", ({expect}) => {
    expect.int(3).toEqual(3);
  })
);
```

But that fails to parse with a terrible message/location (note it needs a new set of {} brackets.

part of me thinks reason should just parse this automatically though and reformat it to include the brackets. At least it should give a better error message about the location.

**Comment by jordwalke** [comment]
Another one is when the expression on the right hand side of a match case `=>` is not a valid parse. It doesn't recover at the next `|`. Simplest case: Just omit any expression on the rhs of an `=>` in a match case.

**Comment by thangngoc89** [comment]
```reason
open Js_of_ocaml;

let completion = (input) => {
  let input = Js.to_string(input);

  let (startPos, completionList) = Repl.Completion.complete(input);

  completionList |> Array.of_list |> 
}
```

This gives syntax error at `open`

**Comment by anmonteiro** [comment]
the examples here all look fixed.
