### ISSUE TITLE
Weird Indent when using anonymous function with pipe operator

### ISSUE THREAD

**Issue by dawee** [reasonml/reason#2385]
`refmt` choose to end a processing function like `List.filter` at the same column where the function started. It makes sense, but everytime I'm using a pipe operator with anonymous functions I'm getting this kind of results:

```re
let result =
  list
  |> List.filter(
       fun
       | `data => true
       | `error => false,
     )
  |> List.length;
```

It's bugging me a bit everytime I read it because it doesn't align well with the flow. Specially when you're in an editor like VSCode, it feels like the function is not at its place:

![Screen Shot 2019-04-16 at 4 50 12 PM](https://user-images.githubusercontent.com/1039076/56243088-bc62cb80-6067-11e9-80cb-394e8eb24a1e.png)

Personally I would have expected this:

```re
let result =
  list
  |> List.filter(
    fun
    | `data => true
    | `error => false,
  )
  |> List.length;
```

So that every line starts at a modulo of 2:

![Screen Shot 2019-04-16 at 4 55 16 PM](https://user-images.githubusercontent.com/1039076/56243442-9853ba00-6068-11e9-94f8-bfecac28daa9.png)

**Comment by dawee** [comment]
@yawaramin proposed another approach:

```re
let result = list
  |> List.filter(fun
    | `data => true
    | `error => false)
  |> List.length;
```

It also works for me because it fixes the alignment of always starting on a "modulo 2 column". Plus it seems to be fairly close to what `ocamlformat` would do.

**Comment by anmonteiro** [comment]
discussing this in #2675
