### ISSUE TITLE
Support for refactoring.

### ISSUE THREAD

**Issue by cristianoc** [reasonml/reason#239]
A bunch of thoughts for nice-to-have features in future.

The existing infrastructure for mapping ocaml's `=` to Reason's `==` and other operators seems a clear first step towards supporting refactoring. Specifically, it's already a form of renaming.
By working at the level of the AST it will be possible to support reasonably safe refactoring operations to be surfaced with editor plugins.
One aspect that will not be covered is refactoring inside comments. However, by supporting structure in comments to reference actual code (e.g. for documentation), it should in principle be possible to extend refactoring to comments too. (And, give support for catching when comments go out of synch with code changes).

**Comment by anmonteiro** [comment]
ocaml-lsp + merlin + upcoming support for project-wide occurrences will support this
