### ISSUE TITLE
Outcome printer incoherence with conjunctive types

### ISSUE THREAD

**Issue by Octachron** [reasonml/reason#2396]
When printing conjunctive types, like
```Reason
type t = pri [< `X &(int) &(float)];
```
the outcome printer outputs:
```Reason
type t = pri [< `X &(int & float)];
```
which cannot be parsed back by reason parser.

(Note that conjunctive types are mostly a type-checking artefact, an they are not really intended to be used directly, so the incoherence is quite minor.)

**Comment by anmonteiro** [comment]
not reproducible in master

```shell
$ dune exec refmt
type t = pri [< `X &(int) &(float)];

type t = pri [< | `X&(int) &(float)];
```
