### ISSUE TITLE
Reason_toolchain error

### ISSUE THREAD

**Issue by rickyvetter** [reasonml/reason#2413]
Hey folks. @bloodyowl and I are running into some issues upgrading the Reason dependency on `upgrade-reason-react`. It appears as though `Reason_toolchain` may not be working on newer versions of Reason. Any thoughts on how we should proceed? Are there working examples of Reason_toolchain?

```
❗️️ Errored on output/test/cases/App.re
Invalid_argument("index out of bounds")
Raised by primitive operation at unknown location
Called from file "menhirLib.ml", line 1334, characters 10-36
Called from file "reason_toolchain.ml", line 613, characters 27-48
Called from file "reason_toolchain.ml", line 653, characters 10-67
Called from file "reason_toolchain.ml", line 711, characters 14-50
Called from file "reason_toolchain.ml", line 861, characters 22-55
Called from file "reason_toolchain.ml", line 198, characters 16-34
Called from file "reason_toolchain.ml", line 935, characters 8-13
Re-raised at file "reason_toolchain.ml", line 958, characters 17-18
Called from file "reason_toolchain.ml", line 301, characters 8-63
Re-raised at file "reason_toolchain.ml", line 260, characters 16-144
Called from file "/path/to/upgrade-reason-react/src/migrate.re", line 107, characters 15-116
Done!
```

I've created a branch that basically doesn't do any ast transform as all. I'm just detecting file type, parsing, and printing. It should be the same as running refmt with the correct flags on a file. You can try it out here:

```
git clone git@github.com:rickyvetter/upgrade-reason-react.git
cd upgrade-reason-react
git checkout update-refmt
yarn
yarn test
```

**Comment by IwanKaramazow** [comment]
Looking into the problem

**Comment by bloodyowl** [comment]
@IwanKaramazow https://github.com/bloodyowl/upgrade-reason-react-esy using reason from opam works, it seems it's related to bspacks/refmt_api itself

**Comment by anmonteiro** [comment]
not reproducible
