### ISSUE TITLE
Enhancing releases section of repo

### ISSUE THREAD

**Issue by raiyanalam** [reasonml/reason#2418]
Hi,
The releases section in this repo does not provide any information on the changes incorporated in the release. 
![image](https://user-images.githubusercontent.com/7879476/59022273-12374100-886b-11e9-993b-44d61461b7eb.png)

It would be great if with each release a list of changes are displayed or even a simple link to changelog would also help. Also, GitHub will notify watchers every time a new release is available.
Solution wise, since the repo already uses Azure pipelines for CI, we can potentially leverage its [built-in task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) to publish release notes to GitHub. The task can be configured to create a release only when the pipeline is triggered for a matching tag. It can compute an exhaustive list of changes done in this release, list them and cross reference it with the issues. Additionally, we can also provide a list links to external sources which we think will be useful for users to get started with the release.
Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability. Being a built in task, this can be achieved with minor changes to the CI file.
 
PS: I am a PM for azure pipelines. I would be happy to help with the changes :)

**Comment by raiyanalam** [comment]
@jordwalke

**Comment by davesnx** [comment]
Last few releases contain minimum information but it's hand-written. 

It would be great to have the GithubRelease task as part of the CI, would you like to setup something?

**Comment by anmonteiro** [comment]
they do now
