### ISSUE TITLE
Better documentation/Syntax for redundant option types for named parameters

### ISSUE THREAD

**Issue by aweis** [reasonml/reason#2425]
**My Goal:**

I was working on a serializer for reason records to JSON objects using `[@bs.obj]`.  I wanted to mark my reason records with optional keys, and when they were serialized with `None` values, the key itself will not appear in the resulting JSON.

for example:
```
type t = {foo: string, bar: option(string)}

let v = {foo: "value", bar: None}
```
should be serialized to the following:
```
{"foo": "value"}
```
**My Implementation**
here is my `[@bs.obj]` function:

```
[@bs.obj]
external bsObjMake:
(~foo: string, ~bar:string=?, unit) => _ = "";
```
and calling the function as so
```
let convert = ({foo, bar}) => bsObjMake(~foo,?bar,());
```

**How I was confused**
It confused me that I was accidentally declaring my bsObjectMake function with the following signature:
```
[@bs.obj]
external bsObjMake:
(~foo: string, ~bar:option(string), unit) => _ = "";
```

**My ask**
Is there a way to somehow give a warning to the user that they are not using the `=?` and `?` syntax at the call correctly?

Thanks to the Reason team for building such a great tool and ecosystem.

CC @bobzhang

**Comment by jordwalke** [comment]
Open to concrete suggestions, and I'm curious if [this sketch](https://sketch.sh/s/qOJ6mx4EqFV9pw8YfzOxjL/) I made explaining optional argument syntax is at all helpful in understanding the current features/syntax.
