### ISSUE TITLE
List & Array docs outdated?

### ISSUE THREAD

**Issue by mindplay-dk** [reasonml/reason#2435]
On the [List & Array docs page](https://reasonml.github.io/docs/en/list-and-array), you have this:

> ### Usage
> You'd use list for its resizability, its fast prepend (adding at the head), and its fast split, all of which are immutable yet efficient!
>
> The standard lib provides a List module (and its counterpart with labeled arguments, ListLabels).

But then you have this:

> ### Design Decisions
> In the future, we might provide an out-of-the-box list data structure that's immutable, resizable and features all-around fast operations.

Doesn't the first section say you *have* this already?

Maybe the second statement is left over from a prior version that didn't have this?

**Comment by davesnx** [comment]
This isn't there anymore.

Thanks for opening the issue, and sorry for closing an old issue
