### ISSUE TITLE
Up to date reason npm package

### ISSUE THREAD

**Issue by baransu** [reasonml/reason#2456]
The latest npm `reason` package version is `3.3.4` which is over a years old. We want to use it for [reformatting between Reason and OCaml syntax](https://github.com/reason-association/reasonml.org/pull/34) and would be great to have access to up to date `refmt` version. Is there any reason why the package is not updated with every new release?

**Comment by ryyppy** [comment]
Now that I understand the vendoring process I can give more context:
The `bspack.exe` has been removed from recent `bs-platform` releases, which now blocks Reason's `bspacks` scripts to create a single `refmtJS.ml`  bundle and run a build for `refmt.js`.

This apparently happened around 1 year ago I assume.

**Comment by thangngoc89** [comment]
@ryyppy this isn't true. You don't need bspack to produce refmt.js . Probably just lacks of man-power

**Comment by ryyppy** [comment]
This is either solved by merging #2495 (opam based), or finishing work in #2153 (esy based)

**Comment by jchavarri** [comment]
@thangngoc89 You mean refmt.js could be produced using a regular dune + jsoo setup? How would bucklescript compilation work? (side note: I always thought bspack was created originally because BS was a fork of OCaml and so could not be compiled with regular build tooling, but maybe that assumption is false and that's why I'm confused).

cc @ulrikstrid as we've been discussing about bspack stuff lately :)

**Comment by thangngoc89** [comment]
@jchavarri refmt.js has been always produced by jsoo. Adding bspack into that is just noisy and more complexities for no reasons at all. bspack is for vendoring to bucklescript only

**Comment by jchavarri** [comment]
> You mean refmt.js could be produced using a regular dune + jsoo setup?

So the answer to that is yes?

**Comment by thangngoc89** [comment]
Yes. refmt.js SHOULD be produce by a regular dune + jsoo setup

**Comment by anmonteiro** [comment]
We don’t release to NPM anymore
