### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by nirvdrum** [reasonml/reason#2461]
ReasonML 3.5.1 was just created, but there are no tagged releases since 3.0.4, going back to Dec. 2017. Tags are a very helpful way to check out the source tree corresponding to a release, which is helpful for debugging and creating reproducible builds. Having tags also makes it easy to perform a git diff between two tags to see what's changed.

It'd be great if the tagged releases could be backfilled, but at the very least I hope the new 3.5.1 release provides the opportunity to start tagging as a stage of the release process.

**Comment by aantron** [comment]
Please add tags to the repo. Without tags, the GitHub commit and blame UI are significantly *less* useful. Normally, they display the tags that include a certain commit, which helps with figuring out version bounds and debugging. Obviously, without tags, there is nothing to display.

For example, take this commit: https://github.com/facebook/reason/commit/da280770cf905502d4b99788d9f3d1462893b53e.

GitHub currently shows that it is included in "v.NO", which is the fake release telling users there are no tags in this repo. That's pretty useless.

Please also do legitimate GitHub releases again (simply create them with the button for each tag and paste the changelog). This allows GitHub users to subscribe to release emails from GitHub by watching the repo for Releases only.

**Comment by anmonteiro** [comment]
This is being done now
