### ISSUE TITLE
[feature request] Data-first compose operators

### ISSUE THREAD

**Issue by hoichi** [reasonml/reason#2512]
I know @chenglou warned against excessive point-free programming, but when you pass something like:

```reason
x => x->DoThis->DoThat->AndNowForSomethingCompletelyDifferent
```

you just know you actually describe transformations, not data points, and all you want is actually:
```reason
DoThis->>DoThat->>AndNowForSomethingCompletelyDifferent
```
And by the way, both F# and even Elm (that strives to be as simple as humanly possible) have a compose operators (Elm having both `>>` and `<<`). And given that Reason prefers data-first approach, we probably rather need data-first versions of those operators, hence `->>` or something like that.

What do you think?

**Comment by chenglou** [comment]
Not sure. This makes the intent rather unclear, and you're not actually saving many keystrokes above.

Plus, the first version is actually refactorable. The second one has the reverse architectural effect of inciting refactoring the 3 helpers' declaration site rather than usage site.
