### ISSUE TITLE
Support for css-modules?

### ISSUE THREAD

**Issue by lensbart** [reasonml/reason#2524]
I’m trying to incrementally adopt ReasonML in a large existing React code base. We use [`css-modules`](https://github.com/css-modules/css-modules) for all of our React components: the Sass styles are defined in a separate file per component, preprocessed by several Webpack loaders and bundled into a single `.css` output file.

Styles are loaded as follows:
```jsx
import styles from './index.scss'
const Example = () => <div className={styles.a} />
```
which generates a unique string `styles.a` in order to avoid naming collisions for the `a` class defined in `index.scss`

The Reason docs don’t give much detail regarding the idiomatic way to import CSS into Reason, but they do [mention](https://reasonml.github.io/reason-react/docs/en/style) the popularity of CSS-in-JS.

For us, a CSS-in-JS solution is not preferred as it would be a significant hurdle for adoption, forcing us to refactor most of our Sass. Besides that, having all of the CSS inside the component files would increase the visual clutter (although I see that this is a matter of taste).

Are there any plans for a solution that allows for styles to be defined in separate `.scss` files per component, and to have them bundled, like how Webpack does? In that case it would be trivial to write a script that generates `.rei` interface files alongside every `.scss` file to enable type checking etc., which is possible for TypeScript via `@teamsupercell/typings-for-css-modules-loader`

Thanks!

**Comment by lensbart** [comment]
After watching [the talk by Raphael Rafatpanah](https://www.youtube.com/watch?v=7pu7Fp9nRVg) from the latest ReasonConf, I got a bit further:

```
type css = {container: string};

let styles: css = [%bs.raw {| require('./styles/index.scss') |}];

[@react.component]
let make = () => {
  <div className={styles.container}>
    <FontAwesomeIcon icon=FASpinnerThird.light spin=true />
  </div>;
};
```

Is there already a way to autogenerate the `css` type as used above? Something along the lines of [typings-for-css-modules-loader](https://github.com/TeamSupercell/typings-for-css-modules-loader#readme), which would enable editor integration with autocomplete etc. If not, I might look into it myself, but I wouldn’t want to reinvent the wheel.

Thanks!

**Comment by davesnx** [comment]
Hi @lensbart, Reason has nothing related to handling CSS. I'm working on a solution that works with CSS in a way that could be extracted to work the same way as CSS-modules: https://github.com/davesnx/styled-ppx. 

Closing this issue and feel free to join the Discord and discuss any other viable solution.
