### ISSUE TITLE
refmt: refmt breaks code style

### ISSUE THREAD

**Issue by smorimoto** [reasonml/reason#2527]
I still don't know how to fix this style, but we need to fix this.
https://github.com/reason-react-native/reason-react-navigation/blob/master/src/AppContainer.re#L67-L90

**Comment by davesnx** [comment]
The file isn't there anymore, do you have the snippet that make the code breaking? @smorimoto

**Comment by anmonteiro** [comment]
Closed for lack of activity from reporter
