### ISSUE TITLE
feature request: implement quoted extensions

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#2532]
in ocaml trunk

```
{%raw||}
```
is translated into `[%raw{||}]`
This is a nice addition, since it is pure syntax, we can implement it today

**Comment by bobzhang** [comment]
relevant issue: https://github.com/ocaml/ocaml/pull/8820

**Comment by davesnx** [comment]
Hey @bobzhang, happy to take a look at this. Would you mind giving me a starting point?

Thanks
