### ISSUE TITLE
Is there a tree-sitter-reason package?

### ISSUE THREAD

**Issue by hackwaly** [reasonml/reason#2543]
Textmate syntax highlighting really sucks

**Comment by aryx** [comment]
interested in too.

**Comment by aryx** [comment]
Cool! Then we can add support for reason in semgrep thanks to this tree-sitter-reason.

**Comment by danielo515** [comment]
> Cool! Then we can add support for reason in semgrep thanks to this tree-sitter-reason.

I'll let you know when it reaches a "usable" state. Right now I can't encourage anyone to use it, except those that are willing to contribute to it

**Comment by davesnx** [comment]
There's some effort in here: https://github.com/reasonml-editor/tree-sitter-reason
