### ISSUE TITLE
Online (React) examples not working?

### ISSUE THREAD

**Issue by samkuhn** [reasonml/reason#2546]
Just taking a first look at Reason but the react based examples [ here](https://reasonml.github.io/try.html) all appear to fail with:

> ReactDOMRe.cmj not found, it means either the module does not exist or it is a namespace

Using Chrome 79 on OSX.

**Comment by lessp** [comment]
In the meantime you might want to use: https://nit.sketch.sh

**Comment by anmonteiro** [comment]
Check melange playground https://melange.re/v4.0.0/playground/

**Comment by davesnx** [comment]
Thoughts on redirecting reason/try to melange playground?
