### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#2552]
```reasonml
let h = u => {
    let m = u##hi ;
    m(.1,2);
    m(1 2) // missed ,
}
```

Unclosed "(" (opened line 54, column 5)

This gives me an impression that I have mismatched parens but it is not

**Comment by hasanhaja** [comment]
Hey, this might be a trivial question but I’ve not tried to recreate this yet. Is the line and column count correct?
