### ISSUE TITLE
unknow parser error

### ISSUE THREAD

**Issue by lorenzo-pomili** [reasonml/reason#2553]
Hi I'm reciving strange error after little refactor (I changed string in option(string))

You can reproduce the error from this repo: https://github.com/lorenzo-pomili/workshop_with_train_schedule

last commit introduce the error

**Comment by lorenzo-pomili** [comment]
ok, the error seem disappear removing all the comments in Index.re from line 63 to the end of file,
I pushed branch to preserve error because it look very strange:
https://github.com/lorenzo-pomili/workshop_with_train_schedule/tree/error_branch

**Comment by anmonteiro** [comment]
not a minimal repro
