### ISSUE TITLE
Record syntax within JS objects gets parsed as JS objects

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#2554]
Here's a quick repro case:

```
let foo = {"foo": {bar: 1}};
```

`{bar: 1}` should be parsed as a record but it gets parsed as a JS object instead.

https://reasonml.github.io/try?rrjsx=true&reason=DYUwLgBAZg9jEF4IG8BEsaoFwoEYEMAnHARgF8yBuIA

cc: @rickyvetter 

moved from https://github.com/BuckleScript/bucklescript/issues/4253

**Comment by bobzhang** [comment]
I suggest we give a warning on this case

**Comment by anmonteiro** [comment]
it gets parsed as a record. the outcome depends on how `%mel.obj` gets interpreted.
