### ISSUE TITLE
odd indentation when inlining switch expression inside JSX block

### ISSUE THREAD

**Issue by bsansouci** [reasonml/reason#2561]
It seems like I get 3 spaces indentation when I inline a switch like such:
```reason
<div>
  {switch (x) {
   | 0 => <div />
   | _ => ReasonReact.null
   }}
</div>;
```

This is annoying because VSCode is particular about spacing being in even numbered chunks, so hitting tab on a new line inside the switch always aligns the indentation back to 4 spaces instead of 5 (3 + 2 spaces). It also makes it harder to read because the indentation lines are every 2 spaces, so this looks clearly misaligned with everything else.

**Comment by anmonteiro** [comment]
let's track this in #2675
