### ISSUE TITLE
Last blog post 2018?

### ISSUE THREAD

**Issue by bradennapier** [reasonml/reason#2578]
Just a FYI as someone who has heard about ReasonML multiple times, check out the website, check the blog and see 2018 was the last update and feel the project is dead or not really supported.

I know, I know, my consumption of reason means very little, and this is not meant as a slight in any way, spent a few hours on docs and examples today and it is really awesome what y'all are doing!  Just can be helpful to know how things can be perceived by potential users.

My fault for not taking the time. :-)

https://reasonml.github.io/blog/

**Comment by jordwalke** [comment]
Cool, thanks for the feedback.

**Comment by coetry** [comment]
@bradennapier A lot of the newer community content is being organized at [reasonml.org/blog](https://reasonml.org/blog)

**Comment by anmonteiro** [comment]
we haven't written blog posts in a while, but the [releases page](https://github.com/reasonml/reason/releases) lists the most recent releases.

unlikely there's anything actionable in this one
