### ISSUE TITLE
Confusing documentation for JavaScript Interop

### ISSUE THREAD

**Issue by louy2** [reasonml/reason#2583]
In page [Interop · Reason](https://reasonml.github.io/docs/en/interop), under section [Settling down and getting disciplined about things](https://reasonml.github.io/docs/en/interop#settling-down-and-getting-disciplined-about-things), the code shows:

```reason
[@bs.send] external getContext : (canvas, string) => context = "getContext";
```

But the documentation below says:

> Then we made a `getContext` function, but instead of `@bs.val` we used `@bs.send`, and we used an **empty** string for the text of the external. [emphasis mine]

**Comment by davesnx** [comment]
This isn't part of reason anymore
