### ISSUE TITLE
[refmt] parseRE throws an error when code contains line comment

### ISSUE THREAD

**Issue by jcsherin** [reasonml/reason#2596]
The `parseRE(code: string): astAndComments`  throws an error when the code contains one or more line comments. 

The usage of the JS API is documented [here](https://github.com/facebook/reason/blob/master/USING_PARSER_PROGRAMMATICALLY.md).

```javascript
const refmt = require('reason');

const ast = refmt.parseRE('let x = 1; // line comment');
Thrown: {
  message: '2864: <syntax error>',
  location: {
    startLine: 1,
    startLineStartChar: 12,
    endLine: 1,
    endLineEndChar: 13
  }
}
```

The `reason` package version is `^3.3.4`.

**Comment by anmonteiro** [comment]
this doesn't throw an error anymore, but it takes substantially longer to compile for some reason

**Comment by anmonteiro** [comment]
ends up being the same issue as https://github.com/melange-re/melange/issues/808
