### ISSUE TITLE
Test Checklist for Atom plugins `NuclideReason` and `language-reason`

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#261]
Overview: There are three separate Atom plugins for `Reason`. Not to worry, the user will only deal with one at the end of the day. Two of the three are the _actual_ plugins (syntax highlighting plugin `language-reason`, and the actual IDE integration plugin `NuclideReason`). The third, `atom-reason` is the plugin users install and merely syncs the other two with `opam`.
- `language-reason`: Syntax highlighting plugin (automatically installed)
- `NuclideReason`: Actual IDE/formatting/Merlin integration (automatically installed)
- `atom-reason`: This is the plugin that users _actually_ install. Users don't need to know that the first two exist. Users merely install this one plugin, which will install the other two behind the scenes from the current `opam` installation of Reason. The reason we do it this way, is that the IDE features are tightly coupled to the features of the Reason syntax. We never want them to get out of sync. The user will install `atom-reason`, and that's it - the IDE is kept up to date based on what you have installed in `opam`. `atom-reason` lets them know if there's a new version of the plugin in `opam` to install.
- In order for `atom-reason` to detect that it needs to install new versions of plugins in from the `opam` Reason installation, we need the two other plugins `NuclideReason`/`language-reason` to bump their versions every time a major feature is pushed to them. How can we ensure that we always bump the version?
- What are the main test workflows we need to perform every time we upgrade either Reason or the editor plugins? I'll list test cases below as I think of them:

Test cases:
- You have an existing, older version of the plugins installed, but you upgrade your installation of Reason. The plugins should automatically resync, or at least detect what you need to do to resync them easily.
- You update Reason to a new version, and that new version of Reason has a new added dependency (`npm install/update` should be executed).
- Test with Nuclide installed. Test with Nuclide not installed.
- Test with bleeding edge beta of Atom. Test with stable Atom. Test with internal distribution of Atom.
- We have a new installer plugin called `atom-reason` which installs the other two plugins from `opam`. There's a special field in `NuclideReason` and `language-reason` called `messagesToInstaller` that "sends messages" to the installer. This is so that in case we need to push an update to the two plugins and that in someway needs the auto-installer to update, we can tell the user of the auto-installer "hey, you need to update the auto-installer itself". Otherwise we'd get strange errors. Part of the test plan is to ensure that we can still "send messages" to `atom-reason` (the auto-installer plugin).
- In `atom-reason`, the check box for "Automatically keep plugins in sync with OPAM installation" should be honored.

**Comment by chenglou** [comment]
Stale

**Comment by chenglou** [comment]
Eeeh let's keep it open because the idea's still great
