### ISSUE TITLE
multiple syntax error messages on vscode

### ISSUE THREAD

**Issue by EduardoRFS** [reasonml/reason#2618]
Currently on vscode it only shows the first error message when a parsing error happens, tried with RLS and ocaml-lsp

As pointed by @jordwalke it's probably on the tooling of vscode, as OCaml also shows just a single message, but reporting to keep track

```reason
module X = {
  let a;bc = 123;
};

module Y = {
  let a;bc = 123;
};
```

**Comment by anmonteiro** [comment]
Closing this since it’s an LSP thing
