### ISSUE TITLE
String literals and String module issues

### ISSUE THREAD

**Issue by lojikil** [reasonml/reason#2656]
# Overview

Ok, I worked with @yawaramin (huge thank you to them) on [the ReasonML forums](https://reasonml.chat/t/string-literals-and-string-module-issues/2662/6) to narrow this down. I was clearly misreading the `String` module, so that's fixed; I'll attempt to figure out what the source of Parsing issues I've seen are. Namely, I've had issues strings with escapes, esp `\"`.

I ran into this in a different context, wherein Escaped strings cause the compiler to complain about missing braces, but I ran into a similar edge case today:

```
Reason # let src1 = "\"test\""foo\"";
let src1: string = "\"test\"";
Reason # String.length(src1);
- : int = 6
```

**Comment by yawaramin** [comment]
Discussion in https://reasonml.chat/t/string-literals-and-string-module-issues/2662

**Comment by anmonteiro** [comment]
adding a space to make it obvious this is a syntax error

```reason
let src1 = "\"test\"" foo\"";
```
