### ISSUE TITLE
Fatal error after installing on Windows 10

### ISSUE THREAD

**Issue by MrOcto1** [reasonml/reason#2658]
I'm trying to install Reason on Windows 10 and I get
```
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "create_process", "Path\\To\\NodeJS\\node_modules\\esy\\3/i/esy-3dd856eb/bin/esy.exe")
```
when I run `esy`.

I also had issues during the install. The setup seems to get stuck right after finishing installing (I can see esy.exe in `node_modules\esy` and it creates `esy.cmd` and `esy.ps1` in NodeJS folder) but I get this error when I run `esy`.

NodeJS version: 16.10.0 (Windows Binary (.zip) 64-bit)
NPM version: 7.24.0

Screenshot when install gets stuck:
![Screenshot](https://i.imgur.com/3K13YHU.png)

**Comment by anmonteiro** [comment]
Sounds like an esy issue instead
