### ISSUE TITLE
Format reason codebase with ocamlformat?

### ISSUE THREAD

**Issue by davesnx** [reasonml/reason#2676]
There’s a bit of formatting issues on a few places on the codebase that could benefit a lot from being fixed.

Do we consider an option to adopt ocamlformat and which are the minimum set of options that allow less changes on the codebase?

PS: If we ever do that, we could add an ignored from history commit so it won’t pollute the history (for the ones that care).

**Comment by anmonteiro** [comment]
I'm in favor of this. I've been using OCamlformat in every project and I like not having to think about indentation. PR welcome.
