### ISSUE TITLE
some questions "for what?"

### ISSUE THREAD

**Issue by cybermerlin** [reasonml/reason#2680]
Hi there. I see this language and understand about OCaml, but I don't see any proofs what the difference, what the performance better or worse. I mean, I have javascript\typescript\C#\Go and this languages have different workspaces, tasks and proofs.

When I should use this language and why exactly this lng? - that's the main question.

**Comment by davesnx** [comment]
Hey @cybermerlin, I'm afraid this isn't an issue and rather a question, but nevertheless, I will try to answer it. It's mostly done for me in the docs: https://reasonml.github.io/docs/en/what-and-why.

Reason is the same language (except the syntax) to OCaml, which means: compiler, type-checker, runner, bytecode, dependencies, tooling.

If you have more questions join the Discord https://discord.com/invite/reasonml

**Comment by cybermerlin** [comment]
ok, thank you, btw I saw in documentation only about how it sound good, but why it better than typescript or c# and for what tasks it was created - nothing.
