### ISSUE TITLE
refmt removes parents leading to invalid code

### ISSUE THREAD

**Issue by jchavarri** [reasonml/reason#2724]
Input:

```
let {foo: (_: int)} = 2;
```

Output:

```
let {foo: _: int} = 2;
```

Also applies to `switch` expressions, using destruct in `let` to simplify the repro.

**Comment by anmonteiro** [comment]
What's an example of switch failing?

**Comment by jchavarri** [comment]
Yes, I meant pattern (I think you already figured it out 😄  thanks!)
