### ISSUE TITLE
Pattern-matching of `bool` value is formatted to ternary if we match `true` first

### ISSUE THREAD

**Issue by denis-ok** [reasonml/reason#2733]
When pattern-matching boolean values, it's common to match the `true` value first. However, this approach can lead to undesirable formatting behavior. For instance:

This:
```reason
switch (condition) {
| true => ()
| false => ()
};
```
Formats to:
```reason
condition ? () : ();
```

Sometimes a code style when we first match a shorter branch (with less code) is preferred.
To prevent automatic formatting to a ternary expression in such cases we have to match `false` as a wildcard `_false`.

```reason
switch (condition) {
| true =>
  // short code
  ()
| _false => 
  // long code
  // long code
  // long code
  ()
};
```

**Comment by anmonteiro** [comment]
This has been considered a feature of Reason since the start, but personally it's always annoyed me.

I'm sure some folks depend on it, though, so not sure what to do about it.

**Comment by anmonteiro** [comment]
there's some discussion in https://github.com/reasonml/reason/issues/1700

**Comment by anmonteiro** [comment]
let's follow this in #1700
