### ISSUE TITLE
Open module from another directory

### ISSUE THREAD

**Issue by vadakoff** [reasonml/reason#2736]
Hello guys!

If i have project structure something like:

```
/<project>/
    ./src/
        ./Main.re
        ./Examples/
            ./Greeting.re
```

How can i open module, something like this:
```reasonml
open Examples__Greeting;
```

**Comment by davesnx** [comment]
Depending on your dune setup, but `open Greeting` would be the way.

I will close this since there's no issue, keep asking any question if you have any.
