### ISSUE TITLE
[NuclideReason] Merlin staleness issue

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#275]
This is one of the potentially several causes for Merlin staleness. Repro:
- Add function `bla` to A.re
- Type `A.b` in B.re
- See that there's no autocomplete entry for `bla`.

Inspecting the merlin log file shows that the entry is indeed absent.

Rebuilding the files through CommonML with `npm start` makes everything work again.
@jordwalke says it might be a Merlin & reason problem.

**Comment by anmonteiro** [comment]
dune / merlin / lsp works very well these days
