### ISSUE TITLE
emacs mode minor issues / wishes

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#327]
- [ ] when refmt reports a syntax error, the cursor is not moved to the location of the error, and next-error also does not jump there
- [x] documentation comments don't have a distinct face from normal comments
- [ ] binding occurrence of identifiers in default face (see [screenshot](https://github.com/facebook/Reason/issues/327#issuecomment-217202082))
- [ ] type constructors don't have a distinct face from types
- [ ] `try` not in keyword face
- [ ] `assert` not in keyword face
- [ ] `rec` in `let rec` not in keyword face
- [ ] `lazy` not in keyword face
- [ ] `when` not in keyword face
- [x] `and` isn't in keyword face
- [x] types defined using `and` are not in type face
- [ ] value identifiers defined using `and` are in type face
- [ ] punned record fields are in default face
- [x] calling reason-mode-indent-line at the beginning of a comment line produces: indent-line-to: Wrong type argument: wholenump, -2
- [ ] reason-mode-indent-line does not always agree with refmt (seems to indent all comments 2 columns less than refmt)
- [ ] I missed the default binding of C-c C-c to compile
- [x] I miss tuareg-find-alternate-file normally bound to C-c C-a
- [ ] wrong face for code following identifiers ending in `static`, see screenshot in comment below

**Comment by anmonteiro** [comment]
transferred to https://github.com/reasonml-editor/reason-mode/issues/59
