### ISSUE TITLE
Unifying 'ref' and 'mutable'?

### ISSUE THREAD

**Issue by yunxing** [reasonml/reason#356]
From a beginner's perspective, I find the "mutable" keyword and "ref" keyword are pretty confusing: What's the difference between using `{mutable field: int}` and `{field: int ref}` ? It looks like they are expressing the same intention to have a mutable field.  

I'm thinking if we can unify these two by the following proposal:
- To express a mutable field in a record, use "mutable" keyword as today: `{mutable field: int}`
- Instead of using "let ... ref", use "mutable" keyword: `mutable a = 1`
- Unify ":=" and "<-", use "=" as the universal mutate operator : `obj.field = 1` (we already have this today) and `mutable a = 1; a = 2` (It is written as `let a = ref 1; a := 2` today )
- For const bindings, it is same as today.

**Comment by bslatkin** [comment]
The hard thing for me, as a newbie, is how the `ref` type is the first introduction to mutability in beginner texts like *Real World OCaml*. There it tells you to use `!` and `:=` to read and write `refs`. That doesn't really fit with Reason's more C-like syntax. So it'll probably be hard to hide it from beginners.

It feels sloppy to access `foo.contents` for `ref`s in Reason. I like the idea of using `var` as sugar around a single-field record. I think the simple rule of "if `foo` was declared as a `var`, then replace all occurrences of `foo` with `foo.contents`" will achieve what you want?
