### ISSUE TITLE
Make let and type definitions consistent w.r.t. recursiveness.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#394]
Right now types are recursive by default, and let bindings are not.
I've actually had issues with recursive types by default (and that convinced me of the wiseness of non-recursive bindings in general by default). Should we then make types non-recursive by default (We can easily do this via the syntax (it's just a matter of flipping the defaults)).

**Comment by chenglou** [comment]
Ok, we've decided to do this.

**Comment by anmonteiro** [comment]
as an alternative syntax to OCaml, it makes sense to preserve OCaml's semantics.
