### ISSUE TITLE
avoid dependencies for the core of reason

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#419]
the core part of reason is the parser, which currently consists of these modules: `reason_config`, `reason_utils`, `reason_lexer`, `reason_parser`.

In module `reason_utils`, it used a function `Str.global_replace` which can be easily replaced by a little function. (It introduced dependencies on `str` library, which  is not supported by js backend, also `str` itself relies on c stubs, better to avoid it)

about menhir, according to the manual

>  Can I ship a generated parser while avoiding a dependency on MenhirLib? Yes. One option is to use the code-based back-end (that is, to not use --table). In this case, the generated parser is self-contained. Another option is to use the table-based back-end (that is, use --table) and include a copy of the files menhirLib.{ml,mli}togetherwiththegeneratedparser.Thecommandmenhir --suggest-menhirLibwill tell you where to find these source files.

So, if we use `--table`, we just need check in generated files and two other files `menhirLib.{ml,mli}`

**Comment by bobzhang** [comment]
so for real use (not playground), there is no need to get rid of dependencies on str, the only thing is to check in menhir generated code and (menhirLib.ml(i)), and you are happy to keep the core dependency minimal
see https://github.com/bloomberg/bucklescript/issues/396

**Comment by yunxing** [comment]
@bobzhang Thanks. Now I understand the motivations behind removing the dependencies. I will start working on this soon.

**Comment by yunxing** [comment]
@bobzhang In order to support bucklescript, do you also want us to provide build procedures based on the generated Menhir file, or are you going to integrate it into bucklescript ?

**Comment by bobzhang** [comment]
@yunxing thanks for having a look, I have a pack tool which will bundle all files from reason into a single ocaml file, so there is no build procedure required, we only need the core of reason does not introduce 3rd party dependencies, in that case, I would also need include the source of the third party library.

Btw, `str` is fine, since it is in the core distribution of ocaml

**Comment by yunxing** [comment]
@bobzhang nice, good to know. I will write a replacement for Str.

**Comment by bobzhang** [comment]
@yunxing @jordwalke  is it possible to check in generated ml file from menhir ?  
We do have menhir in production, however, menhir required by reason is the latest one. I see https://github.com/jordwalke/npm-menhir, so I might give it a try if the decision is not checking in generated files, the main issue with npm-menhir is that it takes too much time to dowload and compile and I see no obvious disadvantages if we check in generated files, it would save reason's user's time.

**Comment by yunxing** [comment]
Is it ok if we check in the one generated by --table?

  

Btw the checked-in ml file would be 2-8MB.

  
\--

Yunxing

  

![](https://link.nylas.com/open/2gjtyq1vxam8jgrgiizrfc7pl/local-
3076b2b5-56e9?r=cmVwbHkrMDAwZjg3NTkyODAzOWRhMTU3YjA3MWE2YmY5Njk3Yjg2OTM1MmI1YjYxOWMwZTIxOTJjZjAwMDAwMDAxMTM3YzA4ZTY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 17 2016, at 11:52 am, Hongbo Zhang &lt;notifications@github.com&gt;
wrote:  

>
[@yunxing](https://github.com/yunxing&r=cmVwbHkrMDAwZjg3NTkyODAzOWRhMTU3YjA3MWE2YmY5Njk3Yjg2OTM1MmI1YjYxOWMwZTIxOTJjZjAwMDAwMDAxMTM3YzA4ZTY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=)
[@jordwalke](https://github.com/jordwalke&r=cmVwbHkrMDAwZjg3NTkyODAzOWRhMTU3YjA3MWE2YmY5Njk3Yjg2OTM1MmI1YjYxOWMwZTIxOTJjZjAwMDAwMDAxMTM3YzA4ZTY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=)
is it possible to check in generated ml file from menhir ?  
>  
>  We do have menhir in production, however, menhir required by reason is the
latest one. I see [https://github.com/jordwalke/npm-
menhir](https://github.com/jordwalke/npm-
menhir&r=cmVwbHkrMDAwZjg3NTkyODAzOWRhMTU3YjA3MWE2YmY5Njk3Yjg2OTM1MmI1YjYxOWMwZTIxOTJjZjAwMDAwMDAxMTM3YzA4ZTY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=),
so I might give it a try if the decision is not checking in generated files,
the main issue with npm-menhir is that it takes too much time to dowload and
compile and I see no obvious disadvantages if we check in generated files, it
would save reason's user's time.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/facebook/reason/issues/419#issuecomment-226851786&r=cmVwbHkrMDAwZjg3NTkyODAzOWRhMTU3YjA3MWE2YmY5Njk3Yjg2OTM1MmI1YjYxOWMwZTIxOTJjZjAwMDAwMDAxMTM3YzA4ZTY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AA-HWQbZ-
yN02Th_wVlWSMxHi0O4JJKbks5qMuzmgaJpZM4Iasnm&r=cmVwbHkrMDAwZjg3NTkyODAzOWRhMTU3YjA3MWE2YmY5Njk3Yjg2OTM1MmI1YjYxOWMwZTIxOTJjZjAwMDAwMDAxMTM3YzA4ZTY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AA-HWWiTJ6Pozz3YCrsnJ8mHWdXnyrJDks5qMuzmgaJpZM4Iasnm.gif)

**Comment by bobzhang** [comment]
I think `--table` is the one used in reason, no?

**Comment by yunxing** [comment]
Right. Just wanted to make sure it is ok to bundle a file generated by
--table.  
  
\--

Yunxing

  
![](https://link.nylas.com/open/2gjtyq1vxam8jgrgiizrfc7pl/local-
4a44a215-c1bf?r=cmVwbHkrMDAwZjg3NTlhMWQxNjkyZjlkN2YzNmUxNWY2ZDRiNmMzNTBiYzcwY2M5ZGIwYTY2OTJjZjAwMDAwMDAxMTM3YzI3NGY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 17 2016, at 2:02 pm, Hongbo Zhang &lt;notifications@github.com&gt;
wrote:  

> I think `--table` is the one used in reason, no?

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/facebook/reason/issues/419#issuecomment-226880696&r=cmVwbHkrMDAwZjg3NTlhMWQxNjkyZjlkN2YzNmUxNWY2ZDRiNmMzNTBiYzcwY2M5ZGIwYTY2OTJjZjAwMDAwMDAxMTM3YzI3NGY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AA-
HWV9OvK6JzFbf3OKRubBwASdLVJS1ks5qMwtPgaJpZM4Iasnm&r=cmVwbHkrMDAwZjg3NTlhMWQxNjkyZjlkN2YzNmUxNWY2ZDRiNmMzNTBiYzcwY2M5ZGIwYTY2OTJjZjAwMDAwMDAxMTM3YzI3NGY5MmExNjljZTA5MmM3ZTA2QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AA-HWcOazUcoWgUNwFW2aqfe64NTcBq4ks5qMwtPgaJpZM4Iasnm.gif)

**Comment by bobzhang** [comment]
@yunxing Yes, for --table backend, we also need `menhirLib.ml` and `menhirLib.mli` for the runtime support (for the specific version of menhir). For best performance, people would use `--code` backend to parse it first, when finding an error, it would fallback to `--table` backend for better error message, but it is not necessary.

I would like to spend some time in the next few weeks to integrate the parser with bucklescript, ideally, we should have commands below work out of the box

```
bsc --bs-rest-files *.re *.rei
```

To make this happen and maintainable in the future, my vision of reason parser is that it would be a self contained library, its dependency is limited to the core distribution (it's fine to have more dev-dependencies for example, menhir), do you think this is the right direction?

thanks for looking into this issue!
