### ISSUE TITLE
Consider lighter-weight formatting of parens

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#429]
Proposal: format parens in a more lisp style.  E.g.: change

```
NodeSet.union
  acc
  (
    slice_nodes (
      IList.filter (fun s => not (NodeSet.mem s !visited)) n.nd_succs
    )
  )
```

to

```
NodeSet.union
  acc
  (slice_nodes
    (IList.filter (fun s => not (NodeSet.mem s !visited)) n.nd_succs))
```

and

```
switch (k1, k2) {
| (
  Prune_node is_true_branch1 if_kind1 descr1,
  Prune_node is_true_branch2 if_kind2 descr2
) => {
```

to

```
| (Prune_node is_true_branch1 if_kind1 descr1,
   Prune_node is_true_branch2 if_kind2 descr2) => {
```

and

```
IList.filter
  (
    fun
    | Sil.Aeq lhs rhs
    | Sil.Aneq lhs rhs => exp_contains lhs || exp_contains rhs
  )
  pi
```

to

```
IList.filter
  (fun
   | Sil.Aeq lhs rhs
   | Sil.Aneq lhs rhs => exp_contains lhs || exp_contains rhs)
  pi
```

and

```
(
  removed,
  if !Config.angelic_execution {
    remove_abducted_retvars p'
  } else {
    p'
  }
)
```

to

```
( removed,
  if !Config.angelic_execution {
    remove_abducted_retvars p'
  } else {
    p'
  } )
```

and

```
(
  not (Sys.file_exists dest_file_str) ||
    DB.file_modified_time (DB.filename_from_string source_file_str) >
      DB.file_modified_time dest_file
);
```

to (assuming #410)

```
(  not (Sys.file_exists dest_file_str)
|| DB.file_modified_time (DB.filename_from_string source_file_str) >
     DB.file_modified_time dest_file );
```

**Comment by andreasabel** [comment]
Commata on the left seems more principled:
```
let x =
  callMyFunctionWith
    firstArg
    ( reallyLongTupleItem x y z x y z x y z
    , reallyLongTupleItem x y z x y z x y z )
    thirdArg
    ( reallyLongTupleItem x y z x y z x y z
    , reallyLongTupleItem x y z x y z x y z );
```

**Comment by nmn** [comment]
As someone who's repeatedly failed to get comfortable reading lisp code because of closing parens, I'm extremely against putting closing delimiters on the same line as the wrapped code.

Being able to vertically scan closing delimiters is extremely important for readability.

I prefer this formatting the best:
```
let x =
  callMyFunctionWith
    firstArg
    ( reallyLongTupleItem x y z x y z x y z
    , reallyLongTupleItem x y z x y z x y z
    )
    thirdArg
    ( reallyLongTupleItem x y z x y z x y z
    , reallyLongTupleItem x y z x y z x y z
    );
```

**Comment by bsansouci** [comment]
I prefer @jberdine's original proposal. Lisp-like is more compact and I'd argue not less readable. If your code is very indent, it _will_ be hard to read, no matter where the parens are. The closing parens won't help you much in figuring out what's happening. I'd argue the indentation would be a better cue as to what is an argument to what.

**Comment by nmn** [comment]
My problem with lisp has always been that I can easily see when I enter a scope, but when you're mixing single line constructs with multi-line constructs, it can often get really tricky to see when a scope actually ends.

In the code example in this thread I can read every style just fine. But in complex deeply nested code, It gets really hard to track closing parens when you see `)))))))` at the end of some lines.

**Comment by bsansouci** [comment]
@nmn I can understand the general argument, but I can't picture an actual example where such a nested call would benefit from newlines.

```rust
let test a b c => {
  complexFunction
    (arg1AlsoIsAFunction 
      (a + b) 
      (b * c)
      (longThirdArg a b (blabla (blablalba2 a b c))))
    (arg2AlsoIsAFunction
      (magicalThingsHappenHere
        (heyoThisIsSoFreakingLong 
          (a + 1000) 
          (b - 10000)
          (c * 10000))))
};
```

VS

```rust
let test a b c => {
  complexFunction
    (arg1AlsoIsAFunction 
      (a + b) 
      (b * c)
      (longThirdArg a b (blabla (blablalba2 a b c)))
    )
    (arg2AlsoIsAFunction
      (magicalThingsHappenHere
        (heyoThisIsSoFreakingLong 
          (a + 1000) 
          (b - 10000)
          (c * 10000)
        )
      )
    )
};
```

If I squint hard I can picture some case with a lot of expressions-as-statements being very confusing, but I'd assume that curly braces and semi colons would help delimitate visually.

**Comment by nmn** [comment]
@bsansouci In the given example, I have much easier time reading the second option. The thing here is that when I see a closing paren, I instantly know what it's closing. If it's at the end of a line, I need to go left, if it's at the starting of a line I need to scan up. In the first option, it really doesn't work that way.

Maybe I'm a minority, and if I am, I'll make it work for me. I still manually reformat lisp code every time I need to read it.
But if the divide is not so clear, I don't really see a downside with the second option.

**Comment by jordwalke** [comment]
@nmn I definitely agree with you on the readability part - but this is something that we can easily support without removing your ability to format your code as you like. We need a good system for specifying a project's formatting configuation and using that to specify how to apply wrapping/parens, and number of spacing. I was thinking we could either place it in a `.merlin` file or ` package.json`. @chenglou  and I were thinking about having only a single file called `package.json` per project that would have everything you need to express/install/build dependencies, and I could even see putting other package related info in it such as project formatting configuration. From that one file we could install or generate whatever we needed to to work well with opam/merlin/npm etc.

**Comment by anmonteiro** [comment]
quite outdated, not sure what's actionable here.
