### ISSUE TITLE
Support for opam user-setup

### ISSUE THREAD

**Issue by reynir** [reasonml/reason#512]
It would be great if opam-user-setup had support for Reason so setting up editor configuration (e.g. do the steps in https://github.com/facebook/reason/tree/master/editorSupport/VimReason#installation for vim).

This maybe belongs to https://github.com/OCamlPro/opam-user-setup/.

**Comment by kennetpostigo** [comment]
I think the documentation on the new website and the new [reasonml-editor](https://github.com/reasonml-editor) org should have better documentation for user-setup. Is this okay to close?

**Comment by reynir** [comment]
`opam-user-setup` is a script for automatically configuring your editor(s) etc. to use `merlin`, `ocp-indent`, etc., and not just documentation. Better documentation is great news, but sort of unrelated to this issue, I would say.

**Comment by kennetpostigo** [comment]
@reynir oh sorry for the confusion, I misinterpreted what you meant by `user-setup`. However, reason team has a package you can install globally through npm, called [reason-cli](https://github.com/reasonml/reason-cli) that editor plugins in [reasonml-editor](https://github.com/reasonml-editor) org will pick up on and use the binaries it exposes. `reason-cli` generally packages up all the [packages you need for reason development](https://github.com/reasonml/reason-cli#included-binaries). However I don't believe it exposes `ocp-indent`. Maybe @jordwalke or @chenglou could determine whether it is something that we want to include or that enough people from the community think this is necessary.

**Comment by bassjacob** [comment]
reason-cli also won't work for people who don't want to mix-n-match the opam versions with the npm versions.
