### ISSUE TITLE
applying refmt often confuses emacs into thinking parens & braces are mismatched

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#522]
I don't have a good repro for this yet, but when applying refmt, emacs often gets out of sync and reports that parens and braces are mismatched for large segments of code.  I have observed this only with reason code, sometimes when applying refmt manually, sometimes through the save hook.

**Comment by yunxing** [comment]
I've been seeing this occasionally as well but wasn't able to get a repro for it. Let me try to have a minimum produce steps.

**Comment by jberdine** [comment]
I think this may have something to do with `>` and `<` characters, which seem to be interpreted as needing to be matched like parens.

**Comment by yunxing** [comment]
@jberdine Thanks, that's super helpful!
