### ISSUE TITLE
Complete syntax quick reference guide

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#536]
For people familiar with OCaml, or those unfamiliar but trying to either work from OCaml examples or documentation, it would be very useful to have a quick reference guide that shows how _every_ syntactic construct in OCaml is expressed in Reason.

**Comment by jordwalke** [comment]
This doc specifies all of the primary *difference* http://facebook.github.io/reason/mlCompared.html

What format were you thinking of?

**Comment by jberdine** [comment]
GADTs, let open!, first-class module things,...

**Comment by jordwalke** [comment]
True!

**Comment by kennetpostigo** [comment]
I think [reason-tools](https://github.com/reasonml/reason-tools) helps out with this greatly, is this okay to close?
