### ISSUE TITLE
Warn when shadowing a variable

### ISSUE THREAD

**Issue by bsansouci** [reasonml/reason#553]
As it stands currently, Reason will not error when you do something like:

``` rust
let a = 5;
let a = a + 6;
```

I'm not a fan of that because it has only be unintentional so far, and unfortunately sometimes the types are coherent rendering the type checker useless. When working on [rewitness](http://github.com/bsansouci/rewitness), our little game written in Reason, we hit this issue at least twice where we were accidentally shadowing a variable, and then had to refactor a bunch of code which meant moving variables around scopes and then things started to error out in confusing ways. Part of the reason it took us longer than expected was because I didn't expect shadowing to happen silently like this.

I can see it being useful for re-assignment but I think having a more approachable syntax like

``` rust
let a = 5;
a = a + 6;
```

would be maybe less error prone. Then the compiler could warn/error when shadowing.

I do remember seeing this pattern in OCaml though, where you define a helper function called `doSomething` and then right below you shadow that helper with the same name but with the "public interface" of that function. I always found that extremely confusing because it's hard to know which one is getting called where, and you can't just grep for that name in the file.

**Comment by Schmavery** [comment]
I think this particular solution to the shadowing problem will result in unintuitive-looking scoping, especially for programmers used to imperative programming.

```ocaml
let a = "foo";
if (b) {
    a = "bar";
};
print_string a /* this always prints foo */
```

I think in this example, some programmers might expect "bar" to be printed when b is true.  IN a lot of languages this would be reassignment but here we're actually shadowing a within the scope of the if block.  I'd say it would be nice to be able to potentially get this warning/handle shadowing more explicitly, but this probably isn't the solution.

**Comment by jordwalke** [comment]
I think a "linting" level warning would be best. Many people (myself included) like and use the lightweight shadowing occasionally, but I totally understand that others don't. We can have it be a linting warning enabled by default.  (I wonder if there's already an `ocamlc` warning for it)

**Comment by chenglou** [comment]
JS lints this and it's been mostly noise personally.
The proposal:
```rust
let a = 5;
a = a + 6;
```
is misleading because it might be confused with _actual_ mutation. This code fails:
```rust
let a = 5;
if foo {
  a = a + 6;
}
```
So I'd rather not confuse people with mutation vs convenient shadowing.

**Comment by cristianoc** [comment]
@bsansouci on rewitness:
```sh
$ rebuild -pkg lablgl.glut -cflags "-ppx InferML" src/index.byte | grep XXX
XXX: variable nextTile shadowed in File "src/index.re", line 407, characters 37-45 (previously bound at line 406)
XXX: variable x shadowed in File "src/index.re", line 518, characters 17-18 (previously bound at line 500)
```

**Comment by bsansouci** [comment]
@cristianoc Ooooh nice!

**Comment by sgrove** [comment]
@cristianoc That does look very nice! Will it also work across files/modules? I refactored some (OCaml) code like:

```
let posts =
 ["a"; "b"]

let my_fun db posts =
  render posts
```

to
```
(module Site)
let posts = 
 ["a"; "b"]

(module Main)
let my_fun db posts =
  let open Site in
  render posts
```

And it caused me some frustrations trying to track down why different values passed as the `posts` arg to `my_fun` weren't working (this is with a Mirage unikernel site, so the retry cycle was a few seconds, and I wasn't sure what part of my stack I had messed up). Sadly, the types matched here, so there was no warning about the source of the issue (shadowing).

**Comment by jordwalke** [comment]
@sgrove: The compiler warning `44` might work for you in that case:
http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec237

**Comment by sgrove** [comment]
Sorry, I should have mentioned that I eventually found that as well (I tend
to turn on a lot of warnings these days), but just for the context of this
thread, even with the great tools, etc. - especially as a beginner -
shadowing can cause some painful experiences.

**Comment by bobzhang** [comment]
I find shadowing is a nice feature, but it makes sense to have explicit shadowing, 
```ocaml
let a = 32 in 
let! a = a + 2 (* quick hack *)
```

**Comment by michipili** [comment]
As you point out using shadowing (i.e. re-letting an identifier) is rather customary in ML:

> I do remember seeing this pattern in OCaml though, where you define a helper function called doSomething and then right below you shadow that helper with the same name but with the "public interface" of that function. I always found that extremely confusing because it's hard to know which one is getting called where, and you can't just grep for that name in the file.

I use this only scarcely, as it has its downsides, but sometimes, it is nice to have.

Probably the right approach would be to make this an optional warning and make it part of the set of “beginner's level recommended warnings.”

@bobzhang OCaml syntax is quite complex but most of the time for good reasons, and we should probably avoid *adding* to this complexity.  Using compiler warnings to report shadowing if the user wants it seems to be a decent solution, which does not require to modify the syntax itself.

**Comment by bsansouci** [comment]
Ok that sounds good to me.

**Comment by jbrownson** [comment]
How about treating shadowing in the same scope different than shadowing in more inner scopes?

i.e. 

```
let a = 5;
a = a + 6;
```

complains because both `a`s are bound in the same scope, and

```
let a = 5;
if foo {
  a = a + 6;
}
```

succeeds since the new a is defined in a more inner scope?

This wouldn't help w/ the scenario @michipili points out of course.

Disclaimer: I don't actually know ML/Reason yet, and am making assumptions based on my knowledge of other languages, maybe this is a horrible idea for ML for some reason I'm not aware of.

**Comment by anmonteiro** [comment]
shadowing is a feature of the language.
