### ISSUE TITLE
command to wrap comments

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#562]
In tuareg-mode, tuareg-indent-phrase when invoked from a comment will wrap the comment to the fill-column.  There should be an analogue in reason-mode.

**Comment by jordwalke** [comment]
👍 
I use this in Vim all the time.

**Comment by chenglou** [comment]
should this be in the reason plugin or up to the editor? In ST and Atom they're handled by their respective general comment/line wrapping plugin. Atom's one (https://atom.io/packages/autoflow) works well with ocaml's `(* *)` but not with reason's `/* */`.

If we default to `//` comment the reflow should just work, without implementing anything from our side.
