### ISSUE TITLE
Automatic package exploration powered by Github.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#600]
When we have opinionated conventions around authoring and forming packages, we can do some really cool things. Here's what I'm thinking, but feel free to mention whatever cool ideas you have.

Imagine automatically crawling all of github and looking for anything that appears to have a `Reason` package configured. We can create a way to browse the entire dependency graph of open source `Reason` packages, and do the following:
- Automatically generate beautiful documentation for each one.
- Create a source browsing/literate mode documentation for each package.
- Build a UI on top of it that allows you to hover over any item and see the inferred type of each portion interactively.
- Click on types and terms, to go to definition - even if the definition resides inside of one of its dependencies that are also hosted on github. This entire experience can be constructed simply by automatically pulling/building github packages.
- For all packages that are marked `jsClean:true`, we can build a custom top level in JS and launch an in-browser interactive REPL with that library and all its dependencies loaded. For every node in the dependency graph that you navigate, you would be one click away from launching an interactive REPL to explore that library.
- If the package has an `/examples/` directory, and is marked `jsClean:true`, we can automatically build them and let you load them into the REPL as examples.

If you conform to some conventions that we decide for `Reason`, there's nothing else package authors have to do to make this work.

**Comment by yunxing** [comment]
This is exciting. One more wish : Shows an instruction of how to use this package in your own project.

**Comment by chenglou** [comment]
Should we create a more opinionated magic spec? Things like `examples/` and all. I can just encode them in our [jengaboot](https://github.com/chenglou/jengaboot)

**Comment by jaredly** [comment]
we have redex - do we still want to crawl github?

**Comment by anmonteiro** [comment]
OCaml.org has a good packages section now
