### ISSUE TITLE
Nit: change downto and upto in for loop to something else

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#628]
I can never remember whether these are inclusive or not. Same for other languages' e.g. `loop 1..10`, `loop 1...10`, etc. Swift is nice in this aspect because it's pretty clear that `for index in 0..<3` is exclusive.

**Comment by ak3n** [comment]
What about `downto` loops?

And how to deal with float literals? This is not correct right now: `0...10`, only `0 ...10` or `0 ... 10` (same thing for `..<`).

**Comment by anmonteiro** [comment]
Reason has `for .. to ..` and `for .. downto ..` to match OCaml.
