### ISSUE TITLE
Postfix syntax for variants

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#637]
Most probably not gonna work out because of the sheer number of parsing conflicts it'll create. But I'm filing this anyway. The reason I'm wondering about this is for simulating units, e.g. `1Px`, `50Percent`, `1min`, etc. They'll be desugared to e.g. `Px 1` and you'd prevent accidental mis-addition of two incompatible units together.

**Comment by jordwalke** [comment]
It actually wouldn't create many parsing conflicts I believe because these would in theory be extracted in the tokenizer. The question is just a matter of specifying *which* variants should be lexed/parsed/printed this way.

**Comment by yunxing** [comment]
One trick I was thinking is to add an attribute to the node, annotating how it should be printed. 

If we eventually have our own ocaml printer, we can just ignore that special attribute.

**Comment by jordwalke** [comment]
Yeah, that would work. Is there any precedence for postfix sugar in other languages? tbph, the set of code that I'd want unit of measurement tracking are exactly the cases where I would not want to pay for the extra boxing of a variant tag.

**Comment by Schmavery** [comment]
Hopefully wouldn't conflict with anything trying to use [extension literals](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec253)?

**Comment by saschatimme** [comment]
This would be really neat for a CSS solution like elm-css!

**Comment by cullophid** [comment]
I just starter working on https://github.com/SentiaAnalytics/bs-css.
This would be majs it much nicer
