### ISSUE TITLE
Make editor plugins look inside `node_modules` to load `Merlin` editor support.

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reason#648]
Currently, this is how the editor support is loaded (please correct my Emacs knowledge)
- Vim/Emacs: We require that you put in your `.vimrc` a line that adds the global OPAM switch to the search path for plugins. That opam switch has the core `Merlin` support for Vim/Emacs/Atom, and the opam switch also has the `Reason` plugins as well. So we tell Vim users to add a bunch of lines [bunch of lines](https://github.com/facebook/reason/tree/master/editorSupport/VimReason) that result in the right directories being in Vim's search paths.
- Atom support is a lot more elegant. The user only needs to install one wrapper/dummy plugin called [atom-reason-loader](https://atom.io/packages/atom-reason-loader), which basically searches for your opam switch automatically.

Now that `merlin` may [now be installed as an `npm` dependency](https://github.com/npm-ml/merlin/releases/tag/npm-2.3.1) of your project, we can improve the plugin loading experience in the following ways.
- [ ] Make two wrapper plugins, that do what `atom-reason-loader` does by dynamically loading the _real_ editor plugin intelligently based on installation of `Reason`/`merlin`. But let's do better than `atom-reason-loader`. Instead of just searching the global `opam` switch, let's search the closest reasonable `node_modules` directory for the first `.re/.rei` file opened.
  - [ ] Create wrapper plugin for Vim
  - [ ] Create wrapper plugin for Emacs
  - [ ] Enhance `atom-reason-loader` wrapper plugin that already exists for `Atom`.

**Comment by jordwalke** [comment]
Currently, this is how the editor support is loaded (please correct my Emacs knowledge)

- Vim/Emacs: We require that you put in your `.vimrc` a line that adds the global OPAM switch to the search path for plugins. That opam switch has the core `Merlin` support for Vim/Emacs/Atom, and the opam switch also has the `Reason` plugins as well. So we tell Vim users to add a bunch of lines [bunch of lines](https://github.com/facebook/reason/tree/master/editorSupport/VimReason) that result in the right directories being in Vim's search paths.

- Atom support is a lot more elegant. The user only needs to install one wrapper/dummy plugin called [atom-reason-loader](https://atom.io/packages/atom-reason-loader), which basically searches for your opam switch automatically.

Now that `merlin` may [now be installed as an `npm` dependency](https://github.com/npm-ml/merlin/releases/tag/npm-2.3.1) of your project, we can improve the plugin loading experience in the following ways.

- [ ] Make two wrapper plugins, that do what `atom-reason-loader` does by dynamically loading the *real* editor plugin intelligently based on installation of `Reason`/`merlin`. But let's do better than `atom-reason-loader`. Instead of just searching the global `opam` switch, let's search the closest reasonable `node_modules` directory for the first `.re/.rei` file opened.
  - [ ] Create wrapper plugin for Vim
  - [ ] Create wrapper plugin for Emacs
  - [ ] Enhance `atom-reason-loader` wrapper plugin that already exists for `Atom`.

**Comment by jordwalke** [comment]
We discovered that it should be as easy as:

- Upon first opening of `.re`, `.rei`, `.ml`, `.mli`, do the following:
  - Search for the closest ancestor that has a `package.json` with an `node_modules` folder in it.
  - From within the editor process:
  - Run the following shell command `eval $(./node_modules/.bin/dependencyEnv)` which will augment the PATH with all the right locations that include `ocamlc/ocamlopt/refmt/ocamlmerlin/ocamlmerlin-reason` etc.
  - Then and only then should `ocamlmerlin` be started.

Then everything should work just as well as it does today! It should be pretty easy if you know how to execute the output of `dependencyEnv` inside of the editor process, so that all forked processes will have the updated `PATH`.

**Comment by yunxing** [comment]
I uploaded a very early version for emacs here:
https://github.com/yunxing/yarn-reason

**Comment by freebroccolo** [comment]
I have also done something similar to what @jordwalke described for the vscode plugin. However, I think it would be a bit cleaner if we could get `dependencyEnv` to just spit out key-value pairs (at least as an option) instead of having it run and modify the environment itself. That way you can just set the intended environment directly when spawning the child process.

**Comment by jordwalke** [comment]
Is it more difficult to set the environment variables by running `dependencyEnv`?

**Comment by freebroccolo** [comment]
@jordwalke I think so. Giving an example with node (which affects the vscode plugin) you can't just use `child_process.spawn` anymore to start merlin.

One alternative is to use `child_process.exec` and do something like `dependencyEnv && ocamlmerlin` but that causes problems for the communication process with merlin due to `exec` buffering the IO. If you start merlin this way and try to use readline, eventually the process will die.

The other way is to stick with `child_process.spawn` but call `sh -c "dependencyEnv && ocamlMerlin"` instead of `ocamlmerlin`. But this seems more fragile and likely to fail on certain systems than if you could just get the key-value pairs and only call `spawn`.

**Comment by KidkArolis** [comment]
Are any of the editors already supporting this? Trying to get reason running locally, failed to install opam.. but the npm version works great. However, struggling to get any of the editor (atom, sublime) integration going.

**Comment by freebroccolo** [comment]
@KidkArolis the vscode extension works this way now. For the other editors, I think you need to start them with `npm run editor` to pre-configure the environment.
