### ISSUE TITLE
wish: IDE command to insert comment attached to current node

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#654]
It would be great to have an emacs/atom/etc command that would insert a comment wherever necessary so that it will get attached to the ast node of the cursor.  Perhaps with an even fancier version where repeated invocation of the command would widen the scope (traverse the ast toward the root).

**Comment by jordwalke** [comment]
Sounds cool. I also commonly want to annotate the closest function.

We can use type information from merlin to auto-populate a comment placeholder. The screenshot shows what I have in Vim for JavaScript. You can tab through the comment placeholders and fill it out like a "form". I'm sure there's a way to do it in Atom too (+ Emacs)

<img width="306" alt="snippet" src="https://cloud.githubusercontent.com/assets/977348/17239891/56b58330-551c-11e6-98e5-37ea83864ade.png">

**Comment by yunxing** [comment]
Traversing the ast upward could be hard, at least in emacs (traversing s-exp upward is easier though). Maybe the best place to do this is in Merlin?

**Comment by jordwalke** [comment]
Yeah, Merlin already has a command :MerlinGrowEnclosing. It's great. It expands the AST selection upwards and highlights it while showing the inferred type.
