### ISSUE TITLE
[atom-reason] Pick up changes to configurations

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#758]
We currently read them once during startup. So it's problematic if the user changes the value. Slightly annoying if the config is wrong, and merlin fails to start up, and then they need to reload the entire editor rather than changing the config value and have it hot reloaded.

Related: we should make sure the environment is picked up at any change, not just during the startup of the editor (where it picks up the right environment variables etc.). People usually have their editor open already; can't ask them to start again for any change.

**Comment by jordwalke** [comment]
Some things like paths to binaries are difficult to dynamically change (merlin has/should have already been started etc). We can subscribe to changes on formatting configs though.

**Comment by chenglou** [comment]
You can kill merlin and restart. This is what you'd have to do if your initial loading fails because of a config error anyway (slightly edge-casey).
