### ISSUE TITLE
[Atom-reason] Redundant type hint at type definition

### ISSUE THREAD

**Issue by yunxing** [reasonml/reason#815]
From @Andrzej Kotulski:

"Type hints in atom are sometimes annoying: they basically make it impossible for me to copy-paste field names because this pops up by default.
I like that atom shows me the type of variables, but showing type of type defined at same point seems redundant to me."

![image](https://cloud.githubusercontent.com/assets/1017689/19498060/11d5bd80-9544-11e6-9ae0-960f6a17f0e1.png)

cc: @chenglou

**Comment by akotulski** [comment]
one suggested solution/workaround is to increase the delay in nuclide settings (from default 200ms to something like 1500ms)

**Comment by vramana** [comment]
The workaround seems to also increase the time it takes for the tooltip to disappear 😞
