### ISSUE TITLE
Document differences of optional args syntax

### ISSUE THREAD

**Issue by jlongster** [reasonml/reason#819]
This is a great page showing the syntax differences between OCaml and Reason: https://facebook.github.io/reason/mlCompared.html

It does not include the differences of labelled/optional args, however. In OCaml you do `~sep:","` but in Reason it's `sep::","`. This seems like an important thing to document.

**Comment by brad-decker** [comment]
@jlongster The linked page is no longer found, assuming that it should reference https://reasonml.github.io/docs/en/comparison-to-ocaml. Can you confirm? Also this issue should maybe migrate to https://github.com/reasonml/reasonml.github.io so people interested in updating documentation may find it easier?
