### ISSUE TITLE
LambdAST

### ISSUE THREAD

**Issue by cristianoc** [reasonml/reason#84]
Just an entertaining thought.
Would it be possible to design a "language for ASTs" to replace the existing parser generators, and the corresponding non existing pretty printers.

Then, Reason itself would be a program: the ocaml AST.

**Comment by let-def** [comment]
It is far from a "language for ASTs", but I am progressing in implementing pretty printing support in Menhir.
The approach is to:
- derive a concrete syntax tree from the grammar
- derive a function that maps a potentially ambiguous concrete syntax tree to an unambiguous one.

To that end, some grammatical rules should be annotated as "semantic identities": the pretty printer is free to insert them to fix ambiguities without changing the semantics.

**Comment by anmonteiro** [comment]
not sure this belongs within the scope of Reason
