### ISSUE TITLE
Fatal error in rtop

### ISSUE THREAD

**Issue by koko256** [reasonml/reason#844]
When #using file:
let newVar () = {
};
the rtop toplevel crashes with
Fatal error: exception Syntax_util.Error(_, _)

utop 1.19.3 ocaml 4.02.3

the correct syntax is processed correctly :
let newVar () => {
};

**Comment by anmonteiro** [comment]
can no longer repro

```reason
Reason # #use "./x.re";
let newVar: unit => {.. } = <fun>;
Reason #
```
