### ISSUE TITLE
Syntax for translating function labels into a record

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#878]
Jordan's idea.

```
let foo bar::b baz::baz => {..*}
```

becomes

```
let foo bar::b baz::baz => {bar: b, baz}
```

Useful for the upcoming react bindings.

**Comment by jordwalke** [comment]
Only challenge is that there is often a final non-named argument. It's not clear what to do with that.

**Comment by chenglou** [comment]
`let foo bar::b baz::baz children => {..*, children}` lol

**Comment by yunxing** [comment]
{..*} looks pretty bizarre to me. In this specific case, I would actually prefer `{bar: b, baz}` better since it is more explicit and keeps the syntax simple -- That being said, I don't know much about the pain in react bindings so I will leave it for you to decide.
