### ISSUE TITLE
[refmt] Do not aggressively format out brackets around function body.

### ISSUE THREAD

**Issue by yunxing** [reasonml/reason#883]
In some cases, it is every hard to edit code back and force if the brackets around function body are removed automatically.
Consider adding a debug line in the function body here:
```
let foo => 1
```
It should be formatted as: 
```
let foo => {
   Printf.printf "here";
   1
}
```
When people remove the debug line later, then it automatically becomes `let foo => 1` again. 

Under this aggressive formatting, it is very painful to go back and forth between this two cases. 

As discussed with @chenglou offline, one idea is to keep the brackets when the function body spans over multiple lines. As an example:
```
let foo => {
   1
}
``` 

stays the same across formatting

**Comment by jordwalke** [comment]
Yeah I agree. The user might want an aggressive cleanup mode too, but certainly during large portion of editing/development I would rather the `{ }` remain.

**Comment by chenglou** [comment]
Bump. This will solve these pesky problems of forgetting semicolons after the braces too

**Comment by yunxing** [comment]
I'm actually curious what would it be like for a explicit {} all the time -- it is less sugary, but more consistent all the time:

let foo => { 1 } 

Also, it helps to differentiate functions from regular bindings: 
let foo = 1;
let foobar () => { 1 };

**Comment by jordwalke** [comment]
I don't feel very strongly but one thing you may always want to support is not having braces if the expression is an infix. This is to at least provide parity with es6. `(a, b) => a + b`

One other feature of our formatter that would be nice is to be able to only group the return expression in {} if the body has any line break. That may require a new feature in our formatting library.

**Comment by yunxing** [comment]
@jordwalke yes, we will need to add some sort of hooks into it.  CCing @pieterv since he has the similar issues with easy format.

**Comment by anmonteiro** [comment]
We fixed this with the preserve braces work
