### ISSUE TITLE
Getting started, Productivity, Barriers, and Feedback

### ISSUE THREAD

**Issue by donnieflorence** [reasonml/reason#885]
I recently discovered reason not too long ago and came across [rewitness](https://github.com/bsansouci/rewitness) which tremendously impressive despite how new reason is. It inspired me to want to learn reason especially seeing rewitness work in the browser and native. However I spent a very very long time trying to find resources to learn reason and try to be productive in it. So I want to write about my experience in an effort to shed light on somethings that reason may possibly do to make it easier to be productive faster. I hope all my feedback is taken constructively because I don't want to offend anyone or put anyone down, I understand how hard it can be to start a new project. I'm really excited about reason! So here goes:

1. I installed reason on my machine to find later that the best way to get started is to use one of the starter projects. It would be helpful to make this a point in the reason readme.

2. There are so many different starter projects, one for web another for native another for rebel. It would be extremely helpful to make a cli that you can install globally and can setup a web or native app structure sandbox. It would be neat to have the reason build system tightly knit into this so that when the build system updates it could be updated similar to how create-react-app/react-native-cli updates. In addition the cli could help with linking dependencies from npm and opam into the app similar to how react native links native packages to your app. This CLI would be really helpful go to resource that encapsulates many of the concerns of the user, i.e. _How do I get started, How do I setup a project, how do I build my project, how do I add dependencies properly, how do I make a production build, how do I optimize._ A centralized tool like this would be helpful and unite several tools. No longer worrying about updating the build system, how to link deps, update reason starter to use newer version of reason, etc. The tool could be responsible of doing all of this for the user. In the future even setup structure for how to scaffold libraries for reason and help publish them correctly.

3. I come from a web background. I'm used to my HTML, CSS, JS. I know how to write markup with HTML, I know how to style and do layout with CSS, I know how to make dynamic things happen with JS. Or even do all these things in JS with libs like React. However I don't know what the primitives for writing markup or styling and doing layout with CSS in Reason. I don't even know how to open a window/program window in reason. All I can do in reason right now is add numbers and curry functions that I learned from the docs on the site. I can't do any of the fun interesting things i'm used to in web like making a webpage, or desktop app, or mobile app. It's not that I can't do things like this in reason. It's that I don't know OCaml libraries for this, especially since the ocaml libs on npm lack docs or OCaml itself from which It seems Reason depends on I find it a little bit silly that to use reason (which is trying to make you forget ocaml) I need to learn OCaml. Though maybe this is because Reason is still very new. Instead of just porting these packages from OCaml it would be helpful to convert them to reason, both source and docs. At least for those not familiar with OCaml or ML.

4. I don't know what the extent of the reason language syntax is. All I know is the syntax basics from the reason site. Seeing as a lot of the syntax is OCaml it would be helpful to add syntax that reason didn't overwrite from OCaml to be re-documented on the reason site. When I say re-documented I mean documented and explained with examples similar to MDN for JS, PureScript, Elm, Clojure, Rust Language GitBook, that have wonderful documentation on all syntax and operators. OCaml docs are pale in comparison even trying to learn and go through them with the reason chrome extension. It's difficult for someone not familiar with ML. Examples, and thorough docs on usage are helpful.

5. Create a package search tool similar to how you search for bower packages. With results only showing reason packages and readme not JS packages. Several of the OCaml packages distributed on npm have little to no documentation and for people not familiar to these packages it doesn't help much to have these packages without documentation to how to use them. Documentation > Packages, Packages without reason documentation for them is not helpful.

I put in a weeks worth trying to be productive in reason. At the end of the week, I was no more productive than the first 10 minutes after the getting a sandbox working and able to add and print things to the console. I'm no programming wizard. I'm an average level programmer. I'm not extremely skilled like many people working on reason and using reason but have sound programming knowledge. The barrier to entry into reason is High in my opinion and not beginner friendly. I'm lucky I didn't have install issues, because I would have probably given up quickly at that point. 

Finally, these are some of the issues that plagued OCaml adoption, the community docs were not helpful to non phd or non ML programmers. Though I see the hard work that everyone in the Reason community is working on changing this to make reason better, providing great build tools, developer tooling, and providing better syntax. I'm hopeful for the future of Reason and the direction its heading towards. 

_You may be thinking, sure point out the obvious and don't contribute to make it better. I wish I could help but I'm afraid my OCaml knowledge is 0. My knowledge on programming programming languages is 0. I'm sorry if I come off as unhelpful or an asshole these are not my intentions. I hope this is all taken constructively and with a grain of salt._

**Comment by jordwalke** [comment]
Great feedback, thanks.

I'll update this issue with things we do to address the points of friction as we get to them.

To start with, I've committed one improvement today that addresses #1. I've updated the main `README.md` to point to `ReasonProject` as the easiest way to install Reason (which is via `npm`). Which instructions were you following and how did you install it, I'm curious. `ReasonProject` has been renamed to `ReasonProject` from `ExampleProject`, because it's more than an example, and that wasn't clear previously. I've also made a well organized site just for `ReasonProject` (https://reasonml.github.io/ReasonProject/). You were not the only one to be confused by this.

We will continue to update this as we deliver improvements. It's quite true that right now, `Reason`'s primary audience is for people who want to help *build* out the Reason/OCaml toolchain so that it's more accessible and approachable. We have some other libraries we'll be releasing this week that make it easier to build web apps.

Thanks for taking the time to write up feedback!
