### ISSUE TITLE
ES6 like template string literals

### ISSUE THREAD

**Issue by bordoley** [reasonml/reason#899]
ES6 string templating is a really powerful addition to javascript. Has any thought been given to adding similar support in Reason? Effectively these expressions could be translated into sprintf calls, although care would have to be taken to choose which format parameters to use by default for integer and float types.

**Comment by vramana** [comment]
This is already a requested feature. @SanderSpies says there are couple of blocking issues before we can get this feature.

**Comment by eriklott** [comment]
Are ES6 template literals still being considered? VDom alternatives like [HyperHTML](https://github.com/WebReflection/hyperHTML) and [LitHTML](https://github.com/Polymer/lit-html) are starting to gain traction, and rely on template literals to work.

It would be exciting to see this feature supported. Adding a view layer to a reasonml app would be effortless...

**Comment by anmonteiro** [comment]
tracking this in https://github.com/reasonml/reason/issues/2603
