### ISSUE TITLE
Array spread support

### ISSUE THREAD

**Issue by bordoley** [reasonml/reason#971]
Reason supports es6 like spread operator for records and lists. Can Reason extends support to arrays as well, translating the syntax to Array.blit function calls?

**Comment by jordwalke** [comment]
Here's a good discussion on that https://github.com/facebook/reason/issues/873

**Comment by yunxing** [comment]
What could be a good syntax for Array.blit here, any suggestion?

**Comment by bordoley** [comment]
Ideally:

```
let x = [| 1, 2, 3, 4|];
let y = [| ...x, 5, 6, 7 |];
let z = [| 5, 6,7, ...x |]
let k = [| 1, 2, 3, ...z, 5, 6, 7 |];
```
The main implementation issue I believe is that there is no ocaml API to allocate an unsafe array, so you would have to hack an implementation. Something like:

```
let sizeK = 6 + (Array.length z)
let k = Array.make sizeK 1; /* Create an initialized array of size with the first item in the array in all positions */
k.(0) = 1;
k.(1) = 2;
k.(2) =3;
Array.blit z 0 k 3 (Array.length z);
k.(sizeK -3) = 5;
k.(sizeK -2) = 6;
k.(sizeK -1) = 7;
```

There might be a more efficient technique (both in terms of code beauty and perf) to implement this, but the meta point is that writing such code by hand is really ugly.

**Comment by hcarty** [comment]
Those could all, somewhat reasonably, be made into `unsafe_set` calls here since the code/logic is generated.
