### ISSUE TITLE
Explicit punning for record field

### ISSUE THREAD

**Issue by bsansouci** [reasonml/reason#977]
It might be useful to have special syntax for record field punning.

Something like `{:x, :y}` instead of `{x, y}`. This would be useful for two cases:
- in the case where we have `let a = {x, y: y - 10};` and we blindly update it to `let a = {x - 10, y: y - 10}` (forgetting to add the key back) we get something like `"Error: 2344: Expecting "}" to finish the block"` (last I checked).
- in the case where we have a record with one field: `{x}` gets seen as a block with the return value `x`. Instead we'd write `{:x}`.

**Comment by yunxing** [comment]
I like this idea for being explicit. 

In the mean time, I don't quite like the idea of having three ways to do the same thing: 
`{:x, :y}`, `{x, y}`, `{x:x, y:y}`. It will look very confusing to new comers. Maybe we should pick one of the forms and print everything to it.

**Comment by SanderSpies** [comment]
I prefer the current punning style, but perhaps we can use a better error message.

**Comment by Schmavery** [comment]
@SanderSpies I agree that the first scenario could be helped with an error message, but the second one seems like a straight up grammatical ambiguity to me.  Ideally I'd have them all print to something like {:x, :y} (like how we print function punning) but that's just me.
