### ISSUE TITLE
Editor macroexpansion

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#993]
cc @freebroccolo for vscode

I'm thinking we can avoid the "dumb", heavy, non-composable file template generation of most other languages by exposing framework-specific ppxes that editors can macroexpand. For example, right now people use e.g. Nuclide/vim/Intellij/whatever template to scaffold a basic react file like

```js
const YourComponent extend React.Component {
  render() {
    return insertJSXHere
  }
}
```

Such heavy tooling to write a few lines of text for me. For OCaml/Reason, we can have:

```
[%react MyComponent]
```

Which we can expand into a similar template. A few advantages of this approach:

- Any library can now define such snippet, instead of upstreaming snippets to e.g. Nuclide
- This is just a specific use-case of macro-expansion. In general I'd use the expansion to peek into the code under the hood for other purposes.
- Non-specific to any editor; heck, no need to implement macroexpansion (roll your own CLI command)
- Composable! `[%commentHeader MyComponent][%react]`

Use the language itself to kill the need for some tools.

**Comment by chenglou** [comment]
Merging #786 into this

> Shouldn't be hard actually. Just pipe the output of ocamlc -dsource -ppx bla ... into refmt and show it.

**Comment by anmonteiro** [comment]
this is supported in ocaml-lsp
